### ISSUE TITLE
Identifying empty string vs nil in MGET

### ISSUE THREAD

**Issue by Resonance1584** [mediocregopher/radix#101]
I'm having trouble determining if a key was set to an empty string in MGET, is there a better way to unmarshal the results of an MGET than what I'm using here?

```
err = pool.Do(radix.Cmd(nil, "SET", "a", "1"))
err = pool.Do(radix.Cmd(nil, "SET", "b", ""))
```

Using redis-cli:
```
127.0.0.1:6379> MGET a b c
1) "1"
2) ""
3) (nil)
```

In Radix MGET
```
var results []string
err = pool.Do(radix.Cmd(&results, "MGET", "a", "b", "c"))
// results {"1","",""}

var results [][]byte
err = r.pool.Do(radix.Cmd(&results, "MGET", "a", "b", "c"))
// results {"1",nil,nil}
```

**Comment by nussjustin** [comment]
Since a string in Go can not be nil, you either need to use a type that can be nil, e.g. a `[]byte` as is your second example, or use a custom `resp.Unmarshaler`.

There is a [MaybeNil](https://godoc.org/github.com/mediocregopher/radix#MaybeNil) type in the `radix` package, that implements `resp.Unmarshaler` and which can be used to check if the result was nil.

**Comment by Resonance1584** [comment]
Thanks, MaybeNil works great for this usecase.
```
results := make([]radix.MaybeNil, len(keys))
for i := range keys {
    var str string
    results[i] = radix.MaybeNil{
        Rcv: &str,
    }
}
err := r.pool.Do(radix.Cmd(&results, "MGET", keys...))
```
