### ISSUE TITLE
Possible wrong value of AvailCount in PoolTrace function

### ISSUE THREAD

**Issue by kimtree** [mediocregopher/radix#107]
Hi Guys, 
I found a possible wrong value in PoolTrace function. The PoolConnectDone function provides `AvailCount` by using len(p.pool), but newly created connection is not added to the pool at this moment (when PoolConnectDone function called). So, AvailCount is not the same as I expected when I check value right after the creation of a new cluster(expect: pool size, actual: pool size - 1).
ref: https://github.com/mediocregopher/radix/blob/a4b003e8968c1faef8f031557bcb25a7cdd70afd/pool.go#L370-L378

Do you guys have any idea to get Pool's current available connection count? IMO, adding interval function in PoolTrace and make it run inside of Pool's atIntervalDo() and get available connection count can be a simple idea. I'll upload a PR for this If you guys agree.

**Comment by mediocregopher** [comment]
Hi @kimtree, sorry it's been taking me so long to respond. It is a bit annoying that using `ConnectDone` won't ever give the correct pool size. At the same time, I don't think using `atIntervalDo` is a good idea, since we shouldn't add a running go-routine for the sole purpose of tracing imo.

One solution, which would also solve another problem, would be to add a `DoCompleted` method to `PoolTrace`, which would get invoked _after_ the `put` has been called (or after `p.pipeliner.Do` has returned). `PoolDoCompleted` would have all the normal attributes of the others, as well as an `DoTime` which would be the total time it took to complete the `Do`, from start to end.

I think this solution will allow you to retrieve a correct pool count frequently as well as provide for other use-cases as well. What do you think? Also, keep in mind that if you need to get the available connection count on-demand there's always the `NumAvailConns` method on `Pool`.

**Comment by kimtree** [comment]
Never mind for responding late 😄  I think the `PoolDoCompleted` would be great and provide completion time for `Do` function is a good metric value for the users.

I remember that there's a `NumAvailConns` method on `Pool`, but I couldn't access it from the Cluster. And also, making another routine for getting `NumAvailConns` periodically and send it to Grafana or something can be an extra logic for me (compare to use `PoolTrace` only)

**Comment by mediocregopher** [comment]
Merged, thanks again! :)
