### ISSUE TITLE
ClusterTopo for determining Masters

### ISSUE THREAD

**Issue by solarfly73** [mediocregopher/radix#110]
Hey Mediocregopher, hopefully this is a quick question.  We were noticing in our test suite that FLUSHALL on teardown of tests doesn't always work, and that's probably because we issued the command against a slave at that moment. To discover the Masters, is the call `ClusterTopo.Primaries()` ?  Does Primaries mean masters?  Thank you in advance!

**Comment by nussjustin** [comment]
> [...] and that's probably because we issued the command against a slave at that moment.

In this case the call should have returned an error, since replicas should reject all writes (and even reads unless you explicitly enable themvia [READONLY](https://redis.io/commands/readonly)).

If you didn't get an error, you probably executed the command against one of the masters, which only flushed the slots assigned to this one master server.

> Does Primaries mean masters?

Yes. `Primaries` returns only servers which act as master. You can loop over the result of `Primaries` and call `Cluster.Client` for each node to get a `Client` for each master.

**Comment by solarfly73** [comment]
@nussjustin thanks for that answer, that's helpful. So the Redis docs say FLUSHALL cascades from masters to slaves, but a slave will only flush data on itself and not propagate. The error we run into on an intermittent basis is that a test will report more/less items in the cache than the test expected because a key wasn't deleted, so we've been trying to figure out what the right way is to get the cluster flushed without resetting nodes and rebuilding it.  Thanks for the reply and your insight!

**Comment by mediocregopher** [comment]
@solarfly73 I think you're question got answered, I'm going to go ahead and close this issue, please feel free to re-open if I'm wrong and you have more questions. Thanks!
