### ISSUE TITLE
Checking for cluster support

### ISSUE THREAD

**Issue by fastest963** [mediocregopher/radix#115]
Right now we have to do something like:
```
err = conn.Do(radix.Cmd(&raw, "CLUSTER", "SLOTS"))
if err == nil {
	var ct radix.ClusterTopo
	var rerr resp2.Error
	if ct.UnmarshalRESP(bufio.NewReaderSize(bytes.NewReader(raw), len(raw))) == nil {
		c, err = radix.NewCluster([]string{ar.Addr},
			radix.ClusterPoolFunc(df),
		)
	} else if uerr := rerr.UnmarshalRESP(bufio.NewReaderSize(bytes.NewReader(raw), len(raw))); uerr == nil && isClusterNotSupportedError(rerr) {
		c, err = df("tcp", ar.Addr)
	} else {
		err = llog.ErrWithKV(errors.New("unsupported response from CLUSTER SLOTS"), llog.KV{"response": string(raw)})
	}
}
```
to check to see if we should make a NewCluster or just have a single connection. It would be nice instead to have some sort of `radix.NewAuto` function that did this since I can imagine more than just us needing something like this.

I feel comfortable making a PR to add this but wanted to discuss first.

**Comment by nussjustin** [comment]
I don't think we should add a function to the package that handles this special case.

This seems like an unusual case. I can't imagine that there will be many users who want their application to transparently work with both clusters and non-clusters. I also don't know of any other Redis library that does this (at least I've never used one).

Also since Redis clusters have some really big restrictions compared to non-cluster instances (e.g. only being able to access keys in the same master or even hash slot), supporting Redis clusters often requires extra care and changes to the way Redis is used from within the application, and once you have the logic in place, you probably don't care about single node usage too much (why go through the hassle to support clusters, when you can run on a standalone node?).

Once the ["official" Redis cluster proxy](https://github.com/artix75/redis-cluster-proxy) becomes GA, users will be able to more easily handle this case by connecting to a proxy, which will also lift some of the restrictions regarding multi key usage.

**Comment by fastest963** [comment]
@nussjustin Definitely understand your point. It's useful to us because we have standalone instances on dev but in production we have clusters so we could transparently use the same code to connect regardless of the environment.

> supporting Redis clusters often requires extra care and changes to the way Redis is used from within the application

I'm not sure what you mean by this. We typically just use a `Client` and we don't have to worry about whether its a standalone or a cluster.

**Comment by mediocregopher** [comment]
@fastest963 I know the way we set things up to use redis was pretty convenient, but I think I agree with @nussjustin in the main here. I don't think it's a use-case that's very common, and implementing it manually isn't that difficult, so I'd rather not add another public function for it.

That said, I think your method of doing the cluster detection could be streamlined a bit, maybe something like this would be simpler?

```go
var res []interface{}
err = conn.Do(radix.Cmd(&res, "CLUSTER", "SLOTS"))
if err == nil {
    // It's a cluster
} else if rerr, ok := err.(resp.Error); ok {
    // It's not a cluster
} else {
    // some other error
}
```

I think that would work fine, unless you needed the `ClusterTopo` for some other reason? If so I think that would be better solved in the other issue you made regarding better error handling in the `ClusterTopo` unmarshaling.

**Comment by mediocregopher** [comment]
Also, I dunno why anyone would want an "official" redis proxy when there's [already one](https://github.com/mediocregopher/breadis), which is so perfect it hasn't been touched since 2015.

**Comment by fastest963** [comment]
To close this out I changed it to be:
```
func isClusterNotSupportedError(err error) bool {
	if err == nil {
		return false
	}
	s := err.Error()
	return strings.Contains(s, "cluster support disabled") || strings.Contains(s, "unknown command")
}
...
err = conn.Do(radix.Cmd(nil, "CLUSTER", "SLOTS"))
if err == nil {
	// is cluster
} else if isClusterNotSupportedError(err) {
	// is not cluster
}
```

**Comment by dokterbob** [comment]
We have a similar use case, specifically; we test on a single node and we deploy on a cluster.
It really would be great to have a similar approach documented somewhere.
