### ISSUE TITLE
Unmarshalling errors

### ISSUE THREAD

**Issue by fastest963** [mediocregopher/radix#116]
From #115:
`radix.ClusterTopo` has no support for unmarshalling an error but I'm not sure how you want that implemented. It might be better to have a radix.Unmarshal(target, resp) helper that attempts to unmarshal into an error so that we wouldn't have to add Error support to all types.

As far as I know all methods _could_ return an error and it seems unnecessary to have to add the same code to all of them but on the other hand, it could cause people to not get the actual errors if they don't use this helper method.

**Comment by mediocregopher** [comment]
You're right that this is a giant hole in the functionality right now, that all the custom unmarshalers in radix don't behave very well if they receive an unexpected type, specifically a `resp.Error`, which would be quite useful (especially, as @nussjustin pointed out in another thread, once [ACLs](https://redis.io/topics/acl) are a thing).

I think the way forward right now is to have a private helper function in the radix package which looks somewhat similar to the `resp2` package's `assertBufferedPrefix` function, except that if it sees the prefix is a `resp2.ErrorPrefix` it would go ahead and unmarshal that error and return it. It also wouldn't consume the correct prefix like `assertBufferedPrefix` does.

This helper could then be used in all `UnmarshalRESP` methods implemented in the main `radix` package. It might end up being a public function in `resp2` one day, but I'm not sure about that atm.

wdyt?

**Comment by nussjustin** [comment]
Sounds good to me

**Comment by mediocregopher** [comment]
So I ended up doing this a different way, but it should work all the same. Basically all the unmarshal functions in `resp2` have been modified to fully unmarshal a RESP error if they see one. This should trickle up to `ClusterTopo`; when it tries to unmarshal the initial array header, if it instead sees a RESP error that will get returned instead. You'll have to use something like `if xerrors.As(err, new(resp2.Error))` to capture it, since it'll be wrapped in an error wrapper. This is probably something I should add to the package documentation.

**Comment by mediocregopher** [comment]
Went ahead and added the docs, gonna go ahead and close this.
