### ISSUE TITLE
make dialSentinel accessible from outside

### ISSUE THREAD

**Issue by yushizhao** [mediocregopher/radix#122]
I think DialSentinel would be convenient to have. So that sentinelOpts is reused. Any concerns not to export it?

**Comment by mediocregopher** [comment]
Hi @yushizhao , what's the use-case for needing to connect to sentinel manually, if someone is using the `Sentinel` client already? Ideally the client would do everything you'd want already.

I'm not sure it's worth adding another publicly facing method in order to do this, it's fairly easy for someone to keep their sentinelOpts around and call Dial manually against the return from `SentinelAddrs`, (which will soon be merged :D).

**Comment by yushizhao** [comment]
For use-case, I am thinking "Force a failover" and "Sub sdown". But yes, you are right, it is not that hard to dial manually.

**Comment by mediocregopher** [comment]
Hmmm interesting, I hadn't considered that someone would want to force a failover. But yeah, that's something that could be done manually easily enough. Going to go ahead and close this.
