### ISSUE TITLE
BLPOP on cluster

### ISSUE THREAD

**Issue by Ximik** [mediocregopher/radix#130]
We have a redis cluster running on AWS. On AWS there is special configuration node, so I start it like

> radix.NewCluster([]string{CONF_NODE})

Everything works fine except for blocking operation

>redis.Do(radix.Cmd(&id, "BLPOP", "key", "0"))

Results with errors like

>read tcp 10.0.2.72:55932->10.0.2.139:6379: i/o timeout

(the first IP is the client node, the second one is the node with "key" on it)

So seems like `radix` doesn't change the timeout logic when switching to another node. Is it bug or I should put some kind of custom timeout function?

UPD: When using `LPOP` the behaviour is even more strange. I receive some values from another keys (which are hash keys). So seems like there is some sort of concurrency issue.

Thank you.

**Comment by mediocregopher** [comment]
Hi @Ximik ! I think your issue is two-fold:

1) You're passing `"0"` in as the `BLPOP` timeout, which means it will block indefinitely.
2) By default all radix connections use a connect/write/read timeout of 10 seconds, see [Dial](https://godoc.org/github.com/mediocregopher/radix#Dial)

So what's happening is redis is waiting indefinitely to send a response to your command, but radix is only waiting 10 seconds, and then returns an error.

*1st Option*

To solve this, you can set the timeout on your BLPOP to be slightly less than radix's, something like `"9"`. 

*2nd Option*

If you want the timeout to be higher, you can increase the read timeout on your radix connections, like so:

```go
// create a ConnFunc which uses a higher read timeout for the connections it creates
connFunc := func(network, addr string) (radix.Conn, error) {
    return radix.Dial(network, addr, radix.DialReadTimeout(20 * time.Second))
}

// create a ClientFunc which returns a Pool whose connections are all made using connFunc
poolFunc := func(network, addr string) (radix.Client, error) {
    return radix.NewPool(network, addr, 10, radix.PoolConnFunc(connFunc))
}

// create a Cluster whose Pools are all made using poolFunc
cluster, err := radix.NewCluster(addrs, radix.ClusterPoolFunc(poolFunc))
// ...

// Use a timeout slightly lower than the read timeout of all the connections.
err := cluster.Do(radix.Cmd(&res, "BLPOP", "key", "19"))
```

I would recommend the second, even if only to set the `DialReadTimeout` to 10 just like the default, because the default might change and it won't be easy to track down why your code is randomly broken again if that ever happens.

Hope that helps!

**Comment by estradino** [comment]
Hey @mediocregopher

What about the LPOP weird behavior we're facing where we receive some values from another keys (which are hash keys)? Seems to be rather some sort of concurrency problem...

Thanks a lot!

**Comment by Ximik** [comment]
Hey, @mediocregopher

Yes, you're 100% right, it was all about the timeout. The problem with random values was caused by a stupid typo. I had `radix.Cmd(r, ...` with `r` being `**struct` instead of `*struct` and havn't noticed that because of errors from `BLPOP`.

Thank you for your great library and support.

**Comment by mediocregopher** [comment]
No problem! Glad it got sorted out :)
