### ISSUE TITLE
Persistent PubSub locked foreverly for Dial errors

### ISSUE THREAD

**Issue by chapsuk** [mediocregopher/radix#153]
Hi, @mediocregopher! Thanks for the awesome package!

[ Create PersistentPubSub](https://github.com/mediocregopher/radix/blob/master/pubsub_persistent.go#L28-L38) has [unlimited loop](https://github.com/mediocregopher/radix/blob/master/pubsub_persistent.go#L86-L91) and it locks all application when connection cant be created. Would be nice get error from PersistentPubSub func if connection not created after N attempts.

Test for reproduce:
```go
func TestPresistentPubSubLock(t *T) {
	createdCh := make(chan struct{})
	go func() {
		PersistentPubSub("", "", func(_, _ string) (Conn, error) {
			return nil, errors.New("incorrect config")
		})
		close(createdCh)
	}()

	select {
	case <-createdCh:
	case <-time.After(500 * time.Millisecond):
		assert.Fail(t, "The call of PersistentPubSub func locked forever")
	}
}
```

Thanks!

**Comment by mediocregopher** [comment]
Hi @chapsuk ! Thanks for bringing this up :) I agree that it's not ideal that calls will just hang forever when redis becomes unreachable. Do you have any ideas of how this could be fixed? I have a few off the top of my head:

1) Add a `PersistentPubSubOpt` type, similar to `DialOpt`, and make an option like `PersistentPubSubAbortAfter(attempts int)` which can be passed into `PersistentPubSub`. This is kind of ugly since it's the only option, and there's already the optional `ConnFunc` argument there which would clash with the new `...PersistentPubSubOpt`.

2) Come up with some kind of signal error: `ErrPersistentPubSubAbort`, which can be returned from the `ConnFunc` to indicate that `PersistentPubSub` should stop attempting and unblock whichever method calls are blocked.

3) Similar to 2, but check if the error returned from the `ConnFunc` implements the method `PersistentPubSubAbort`, and if so stop attempting to reconnect and unblock any blocked methods.

I like 3 because it doesn't require any new types in the API, which is a huge win. On the other hand, if there's ever more options requested for PersistentPubSub we'll wish we'd gone with 1. So it's a bit of a gamble.

**Comment by chapsuk** [comment]
Thanks for the fast answer!

I think 1th is the most clear choice if we agree to up API. 
For 2 and 3 we cant save API, because it require change 
```go
PersistentPubSub(...) PubSubConn
// to
PersistentPubSub(...) (PubSubConn, error)
```
for handle refresh connection error, otherwise `PubSubConn` can be nil and hard to understand whats wrong with connection.

If you agree with the 1, I can prepare the PR :)

**Comment by mediocregopher** [comment]
Hmmm yeah I guess you're right. If you wanna try tackling implementing #1 I'm open to looking at it :)

One thing I kind of want to try though, would be to define the options something like this:

```go
type persistentPubSubOpts struct {
    cf ConnFunc
    abortAfter int
}

type PersistentPubSubOpt interface {
    applyPersistentPubSubOpt(*persistentPubSubOpts)
}

func PersistentPubSubConnFunc(ConnFunc) PersistentPubSubOpt

func PersistentPubSubAbortAfter(int) PersistentPubSubOpt
```

And then have `ConnFunc` implement `applyPersistentPubSubOpt`. From there we can redefine `PersistentPubSub` as:

```go
func PersistentPubSub(network, addr string, opts ...PersistentPubSubOpt)
```

and it would _technically_ be backwards compatible, since anyone using `ConnFunc` before would still be able to do so (though we'd recommend switching to `PersistentPubSubConnFunc`.

What do you think? It _seems_ ok to me, but maybe there's some way where it's not actually backwards compatible that I'm not thinking of (@nussjustin curious about your thoughts too, if you have a moment).

**Comment by nussjustin** [comment]
> and it would technically be backwards compatible

A change in the function signature is still a breaking change, but I don't think anyone would be affected by this and the gain far outweighs this IMO.

**Comment by chapsuk** [comment]
> What do you think?

Think we don't have any chance make it backward compatible in this place, the second return param broke API anyway)

> would be to define the options something like this

I'm not sure about the difference between `PersistentPubSubOpt` as interface or function, both require same changes:

```go
// before
pb := PersistentPubSub("", "", connFunc)

// after
pb, err := PersistentPubSub("", "", PersistentPubSubConnFunc(connFunc))
```

PoolOpt, DialOpt and SentinelOpt is a functions; make PersistentPubSubOpt in same way looks good for me.

**Comment by mediocregopher** [comment]
> Think we don't have any chance make it backward compatible in this place, the second return param broke API anyway

I didn't notice in the PR that the return param changed too, that'll need to be changed back.

> I'm not sure about the difference between PersistentPubSubOpt as interface or function, both require same changes.

The difference is that if it's an interface then we can make `ConnFunc` implement that interface, and anyone who was using the function previously like this:

```
PersistentPubSub("", "", connFunc)
```

will not have their code break.

> PoolOpt, DialOpt and SentinelOpt is a functions; make PersistentPubSubOpt in same way looks good for me.

I agree that it should have been done that way in the beginning, but it wasn't =/ Unfortunately we can't break backwards compatibility, so we'll have to figure out how to make this work without doing so. I think by making `PersistentPubSubOpt` an error, and not having `PersistentPubSub` return an error, we'll be able to do this.

**Comment by chapsuk** [comment]
>The difference is that if it's an interface then we can make ConnFunc implement that interface, and anyone who was using the function previously like this: will not have their code break.

Thanks, now i'm understand what you meant. What you think about https://github.com/mediocregopher/radix/pull/155/commits/a9000ac856f6d068784d2348a66d6e1f4b42312b? 

> I didn't notice in the PR that the return param changed too, that'll need to be changed back.

Sadly, I would like to get the connection error on startup. 
As workaround I call callFunc before create PersistentPubSub for ensure that the connection settings is ok.

>  Unfortunately we can't break backwards compatibility, so we'll have to figure out how to make this work without doing so. 

How about return nil without error?  https://github.com/mediocregopher/radix/pull/155/commits/e68045f994092f9b62196d5a4d92b76b65787218

**Comment by mediocregopher** [comment]
@chapsuk I realized that my plan with ConnFunc implementing the PersistentPubSubOpt interface wouldn't work, because there's cases, like in the Sentinel code, where people would call like this:

```go
p := PersistentPubSub(network, addr, func(network, addr string) (Conn, error) { ... })
```

Since the `func` is being wrapped in a `ConnFunc` implicitly there, changing the signature of PersistentPubSub would break that line.

Rather than keep whirling you around I went ahead and implemented the change in #156 by adding a new function, `PersistentPubSubWithOpts`. It's not pretty, but I don't think there's another way. Thanks for all your help so far in trying to get this to happen, sorry it's been so crazy. Let me know what you think of the PR if you get a chance :)

**Comment by chapsuk** [comment]
Nice work, thanks! 
Publish release, please

**Comment by chapsuk** [comment]
Hi @mediocregopher, would be cool to get the new release tag)
I'm ready to help with blockers

**Comment by mediocregopher** [comment]
For now I recommend just pinning your project to the commit (if you're
using go modules: `go get github.com/mediocregopher/radix/v3@COMMITREF`).
There's a couple PRs I would like to get in before tagging.

**Comment by mediocregopher** [comment]
@chapsuk sorry that took so long, got side-tracked with life. I went ahead and tagged `v3.4.0`
