### ISSUE TITLE
Performance between two types of transaction command

### ISSUE THREAD

**Issue by kimtree** [mediocregopher/radix#163]
Hi @mediocregopher

I've found that my transaction code is quite slower than simple pipeline command. I wonder I am doing wrong with the my code. Could you please give me a hint?

```golang
// This one is super slow. 4x slower than the code below
c.Do(radix.WithConn(key, func(c radix.Conn) error {
	if err := c.Do(radix.Cmd(nil, "MULTI")); err != nil {
		return err
	}

	var err error
	defer func() {
		if err != nil {
			_ = c.Do(radix.Cmd(nil, "DISCARD"))
		}
	}()

	if err = c.Do(radix.Cmd(nil, "INCR", key)); err != nil {
		return err
	}

	if err = c.Do(radix.Cmd(nil, "EXPIRE", key, "3600")); err != nil {
		return err
	}

	if err = c.Do(radix.Cmd(&result, "EXEC")); err != nil {
		return err
	}
	return nil
}
```
vs
```golang

var counts []int64
action := radix.Pipeline(
	radix.Cmd(nil, "MULTI"),
	radix.Cmd(nil, "INCR", key),
	radix.Cmd(nil, "EXPIRE", key, "3600"),
	radix.Cmd(&counts, "EXEC"),
)
c.Do(action)
```

**Edit)** Oh, I found that `Pipeline` command didn't ensure the transaction. Then, what I can do for reducing the execution time with `WithConn` func?

**Comment by nussjustin** [comment]
Pipelines are efficient because they send all the commands to the server without waiting for replies in between. This reduces the overhead of I/O on both sides (radix avoids flushing the underlying buffer after each command and instead only flushes once at the end, after writing all commands).

Since your code waits for each commands reply before sending the next command radix can not buffer the I/O efficiently and Redis needs to switch between I/O (which involves slow syscalls) and command handling all the time.

As long as you don't need to do anything logic between the commands a pipeline should be the best solution. If you need to execute some commands with values that depend on something you need to calculate you won't be able to use the `Pipeline` directly, but you can still emulate one: Instead of calling `c.Do(radix.Cmd(...))` you could put the `CmdAction` into a variable and manually call `MarshalRESP` and then call `UnmarshalRESP` for all commands as necessary. It would probably be even faster to use multiple `Pipeline`s in that case, since they have an optimized implementation that reduces the cost of I/O.

Based on your example I guess that you are currently not using a `Pipeline` because you want to handle all errors, but in that case most of your error handling is really only necessary if you have using commands on keys of wrong types or similar and thus you may be able to avoid most of it. Many automatically be handled by either Redis or the radix package. See also the [documentation on transactions](https://redis.io/topics/transactions#errors-inside-a-transaction), especially this paragraph:

> However starting with Redis 2.6.5, the server will remember that there was an error during the accumulation of commands, and will refuse to execute the transaction returning also an error during EXEC, and discarding the transaction automatically.

An alternative solution would be to use a Lua script. Since Lua scripts are executed atomatically and need only 1 command on the client side, this could be even more efficient (though there is a tiny bot of overhead for Lua scripts, but in most cases you can just ignore this overhead completely).

**Comment by kimtree** [comment]
@nussjustin Thanks for the good explanation! Then, we're trying to use `Pipelining` version instead of `WithConn with DISCARD` since we don't have to check error between `QUEUED` commands which only denotes for syntactically wrong commands.
