### ISSUE TITLE
Hedge request in radix

### ISSUE THREAD

**Issue by dprofeta** [mediocregopher/radix#170]
I would like to implement hedge requests in radix (see https://www2.cs.duke.edu/courses/cps296.4/fall13/838-CloudPapers/dean_longtail.pdf) for more information about it.
This idea is to send multiple requests at the same time to different replicas and to get the fastest one. This reduce the tail latency and improve the resiliency to any redis server crash.

I tried to implement it on top of the current API but it seems quite clunky. I detected so far 2 blocking point to do:
- at connection established, we need to send READONLY primitive to be able to read from slave
- when an action is asked, it has to duplicated and each duplicate sent to a different addr in a dedicated go routine. The first valid reply would go through the API to the client, and the other one would be discarded.

Do you think this is something that could be integrated upstream and it is out of the scope of radix?

**Comment by nussjustin** [comment]
Did you have a particular API in mind?

This sounds like it could be an option for NewCluster and/or NewSentinel, but then we would first need support for sending commands to replicas instead of the master (which is something I wanted for a long time, for reducing load on a master, but never got around to design)

Implementing this for non-Cluster/Sentinel connections would require a new type and would probably be out of scope for radix.

**Comment by dprofeta** [comment]
Yes, it could be done with NewCluster option. That's would be the cleanest I think.
You need an option to enable to use replicas for read query indeed, and an option to say you want to activate hedge queries and how many you want to send at the same time.

For non-Cluster/Sentinel connection, indeed I don't think it is in the scope of radix.

**Comment by nussjustin** [comment]
If we do this I think we should start by adding methods for explicitly sending a command to a replica.

Something like

```go
func (c *Cluster) Read(cmd CmdAction) error
func (s *Sentinel) Read(cmd CmdAction) error
```

We could also try to do this transparently in `Do`, but I personally prefer this to be an explicit choice since replica reads increase the chance of consistency problems and may even increase latency.

Initially we could just choose a random replica on each call and maybe later add more logic to this. When creating the replica connections we could just send an initial `READONLY` command on all connections so we don't need to manage any more state.

@mediocregopher Opinions?

**Comment by nussjustin** [comment]
Ok, forgot that `Cluster` and `Sentinel` instances don't normally hold single connections but pools, so sending `READONLY` on one of the `Client`s wouldn't work as expected.

**Comment by mediocregopher** [comment]
What about a `Client` implementation which was actually just a slice of other `Client`s, and inside of its `Do` method it would do some magic with go-routines and `WithConn`s to hedge the `CmdAction` across all the `Client`s? That seems do-able to me, having not actually tried to do it :P

Sending `READONLY` on a connection is kind of tricky. Let's say we did send it on a connection to a secondary, and that secondary later became the primary, would that connection stay `READONLY`? I think it might, but haven't tested it. If so, then this whole thing would probably have to be separate from `Sentinel` and `Cluster`.

> we would first need support for sending commands to replicas instead of the master (which is something I wanted for a long time, for reducing load on a master, but never got around to design)

The current `Cluster` and `Sentinel` implementations make it possible to pull out a `Client` for secondaries, is there more that needs to be done for that? The only alternative I can think of would be some special `Action` wrapping type which signaled to `Cluster`/`Sentinel` to send the `Action` to a secondary, but that's more special behavior for `Client`s that I'd like to avoid if possible...

**Comment by dprofeta** [comment]
If `Client` is just a slice of `Client`, the logic to keep the same number of `Client` when a `Client` dies, would be quite complicated I think. Also I had in mind to change the slaves targeted at each query, but that's not mandatory.

`READONLY` property is at connection level from redis documentation, so for me, the connection doesn't change when a secondary become primary. If a `Cluster` need both readwrite and readonly query, I think it should have dedicated connection for each kind. So that when a secondary become primary, it just need to change the connection used for the write queries. For my usecase, the `Cluster` would be only readonly, it is another program that make the write queries. 

The issue I encountered while doing a prototype pulling `Client` for secondaries is that the `Action` cannot be reused by multiple `Client`, but I don't see an easy way to copy it. Serializing it and unserializing it seems heavy, just to have multiple time the same `Action` but maybe that's the way to go.

**Comment by nussjustin** [comment]
> The current Cluster and Sentinel implementations make it possible to pull out a Client for secondaries, is there more that needs to be done for that?

Getting a replica is still quiet cumbersome especially if you want to balance across all replicas (for clusters you need to find the replica in the topology and for that you need to calculate the slot first). If the Cluster/Sentinel exposed a way to get a random replica or just execute an Action on a random replica it would be much easier and probably more efficient. 

But setting the `READONLY` on the replica in a Cluster would still be a problem. I don't think there is an easy way to do this with the current API.

For Sentinel we probably wouldn't even need `READONLY` since `READONLY` is just for clusters as far as I remember and a normal non-cluster replica allows reads by default (configurable through the `replica-read-only` setting, which defaults to `yes`).

**Comment by mediocregopher** [comment]
> If a Cluster need both readwrite and readonly query, I think it should have dedicated connection for each kind.

I think that's a lot of extra overhead to support a use-case that the vast-majority of people don't find themselves needing (afaik, i've never heard of anyone else needing it anyway). As you point out, there's quite a few other roadblocks to making this happen, and I think there's some fundamental assumptions that radix makes that this concept breaks (e.g., that an Action will only be taken by a single Conn).

So I'm afraid that this feature will most likely not be implemented/enabled by this project, but if you want you can fork it and change whatever you need to to make it work. In any case, sorry to not be very helpful :(

**Comment by mediocregopher** [comment]
@nussjustin if you want to open a new issue/PR for random replicas we can talk about that there :)

**Comment by nussjustin** [comment]
@mediocregopher Created #174
