### ISSUE TITLE
how to PersistentPubSubWithOpts support  reconnect another host when current connect subcribe err

### ISSUE THREAD

**Issue by orange-jacky** [mediocregopher/radix#178]
hi, 
  i use NewSentinel  to connent redis master-slave with sentinel  of  supporting HA, it's works, meanwhile, i need to subscribe  some channel to recieve message, i read radix of godoc.org, and find 
PersistentPubSubWithOpts can only connect some node of master-slave, and don't support to reconnect another node of master-salve. i need to  subcirbe  supporting high available,
for example , at begining , subcribe node1, and node1 exit from master-slave,  i hope PersistentPubSubWithOpts can subcribe node2 from master-slave, but now it don't support.
can you guide me how to do it ?

**Comment by mediocregopher** [comment]
Hello @orange-jacky , sorry I didn't respond to your issue quickly. Hopefully you figured out a good solution, if not I'd recommend taking a look at: https://godoc.org/github.com/mediocregopher/radix#example-PersistentPubSub--Cluster

It's an example for Cluster, but it would work for Sentinel as well (use Sentinel's `Addrs` method instead of `Topo` to pick an address). Let me know if you have any further questions :)
