### ISSUE TITLE
Cannot connect sentinel radis when select index database

### ISSUE THREAD

**Issue by openkengboy** [mediocregopher/radix#181]
I have connect sentinel redis with select index database first 

```
func NewRedisSentinelConn() error {
        redisHost := viper.GetString("redis.host")
 	redisPort := viper.GetString("redis.port")
 	redisMaster := viper.GetString("redis.master")
 	fmt.Printf("Redis host: %v : %v . primary : \n", redisHost, redisPort, redisMaster)
 	snilClient, err := radix.NewSentinel(redisMaster, []string{redisHost + ":" + redisPort}, radix.SentinelConnFunc(ConnFunc))
 	if err != nil {
 		fmt.Printf("connect sentinel redis err: %v \n", err)
 		return err
 	}
 	snil = snilClient
 	return nil
 }
```

```
func ConnFunc(network, addr string) (radix.Conn, error) {
 	redisIndex := viper.GetInt("redis.cmsindex")
 	fmt.Printf("Redis index: %v \n", redisIndex)
 	conn, err := radix.Dial(network, addr, radix.DialTimeout(5*time.Second), radix.DialSelectDB(redisIndex))
 	if err != nil {
 		fmt.Printf("redis connect err: %v \n", err)
 	}
 	return conn, err
 }
```

```
err := repositories.NewRedisSentinelConn()
	if err != nil {
		fmt.Printf("Cannot connect redis error msg : %#v \n", err)
		os.Exit(0)
	}
```
I get error like this : 

> redis connect err: ERR unknown command `SELECT`, with args beginning with: `15`

I don't know why cannot select dabase. Please help me!!!!

**Comment by mediocregopher** [comment]
Hi @openkengboy , it's a bit difficult to follow your code due to the formatting, I think maybe you want to use a triple backtick block.

Anyway, I think the problem is likely with the option `radix.SentinelConnFunc(ConnFunc)`. What that's doing is telling Sentinel to make connections to the redis sentinel using `ConnFunc`, which is attempting to use `SELECT`, which sentinel doesn't support.

I suspect what you wanted was to use `ConnFunc` for the connections to the actual redis instances, in which case you want to pass in `radix.SentinalPoolFunc` with a function which constructs and returns a Pool, and have that Pool take in `radix.PoolConnFunc(ConnFunc)`.

Hope that helps!

**Comment by openkengboy** [comment]
Thank you for reply. But i don't understand to use `radix.PoolConnFunc(ConnFunc)`. Can you show example code for me?

**Comment by mediocregopher** [comment]
Sure, it's going to be something like this:

```go
func ConnFunc(network, addr string) (radix.Conn, error) {
 	// ...
 }

func poolFunc(network, addr string) (radix.Client, error) {
    return radix.NewPool(network, addr, 10, radix.PoolConnFunc(ConnFunc))
}

snilClient, err := radix.NewSentinel(redisMaster, []string{redisHost + ":" + redisPort}
```
