### ISSUE TITLE
StreamEntry.Fields should be of type []string

### ISSUE THREAD

**Issue by ostcar** [mediocregopher/radix#204]
The redis documentation is ambiguous, if fields in a stream have to be unique. In the [documentation for the XADD Command](https://redis.io/commands/xadd) is written:

`An entry is composed of a set of field-value pairs, it is basically a small dictionary.`

This sounds, as if the field-values are a dictionary and therefore have to be unique. So I understand that radix implements the fields as a map: https://github.com/mediocregopher/radix/blob/a87173feab8aa277c61150fe41673933f92bdf5a/stream.go#L133

But this is not correct. In redis 5 it is possible to add fields with the same name:
```
127.0.0.1:6379> XADD MyKey * foo v1 foo v2
"1587304202845-0"
127.0.0.1:6379> XREAD STREAMS MyKey 0
1) 1) "MyKey"
   2) 1) 1) "1587304202845-0"
         2) 1) "foo"
            2) "v1"
            3) "foo"
            4) "v2"
```

redis 6 will optionally use RESP3 that supports maps. But XREAD will not return a map but an array. The reason is, that streams should preserve the order, and allow for duplicated field names.

More information can be found in the [commit log of the redis repository](https://github.com/antirez/redis/commit/bde1f0a8e).

Maybe the implementation of StreamEntry.Fields should be changed to support duplicated field names and preserves ordner. But of cause, this would be a backwards incompatible change.

**Comment by mediocregopher** [comment]
Thank you for this @ostcar , that's a subtle point but definitely correct. Unfortunately we cannot modify the existing `Fields` field due to backwards compatibility. I see our options as being:

1) Ignore this until radix/v4, which will probably be when RESP3 support is added as well.
2) Add another field to StreamEntry, `FieldsStrings []string` or something like that, which is populated at the same time as `Fields`.
3) Add `FieldsStrings`, but only populate it _instead_ of `Fields` if the `StreamReader` has a certain option set during initialization.

1 is obviously the easiest :P

2 is easy but has a performance penalty associated with it. A large goal of the stream-related code is to have a fast-as-possible implementation of that code available so people don't have to do it themselves, so it would be ideal to avoid hitting performance in this area, especially for an edge-case like this.

3 does not have any performance implications but does add a non-trivial amount of complexity to the API, which is a heavy cost of its own sort.

So it's not a trivial fix, unfortunately. I'm leaning towards 3 but am interested in what others think, and if there's any others solutions that can be thought of.

**Comment by nussjustin** [comment]
If we do something for radix/v3 than I'd go with 3.

**Comment by ostcar** [comment]
Since the final version of redis 6 is [expected to be released in 10 days](https://twitter.com/antirez/status/1245026949812101127) and it seems not so important to change this, I would suggest you keep this issue open for some time and fix it in a v4.

Probably the type [][2]string would be better then []string since the value is a list of field-value pairs.

**Comment by mediocregopher** [comment]
This is listed in the v4 proposal at #212, going to go ahead and close this issue to move discussion there.
