### ISSUE TITLE
Delete multiple keys

### ISSUE THREAD

**Issue by gadelkareem** [mediocregopher/radix#205]
How can I delete multi keys as in https://redis.io/commands/del ?
```
redis> DEL key1 key2 key3
```

**Comment by mediocregopher** [comment]
Hi @gadelkareem , you can have any number of arguments to `Cmd`, so deleting multiple keys would look like:

```
err := client.Do(radix.Cmd(nil, "DEL", "key1", "key2", "key3"))
```
where `client` could be a `Conn`, `Pool`, `Sentinel`, etc...

the `nil` being passed as the first argument to `Cmd` is where the return value from redis would be unmarshaled into, but since DEL doesn't have a useful return value it's not necessary here.

Hope that helps!
