### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by mediocregopher** [mediocregopher/radix#212]
With the release of redis 6 and RESP3 it's about time to cut a new major version of this project. This issue will serve as the proposal and focus of discussion for all development of v4 and all changes for it.

# Development and Release

First a `v4` branch will be cut. Within that branch the codebase will be changed as-needed in order to support the new features we'd like to see. Once ready for release, `v4`'s first commit will be tagged with `v4.0.0`. At that point v3 (`master`) will closed for feature requests; only bug fixes will be allowed from that point onward.

# Changes

Below are changes which are being proposed for v4. Changes which can be backported to v3 should be. `v4` is the opportunity both for supporting new functionality as well as cleaning up existing functionality, so any and all potential backwards incompatible changes are on the table.

## RESP3 Support

Obviously, the big one. The following are proposed:

* Move [resp.Marshaler)(https://godoc.org/github.com/mediocregopher/radix/resp#Marshaler) and [resp.Unmarshaler](https://godoc.org/github.com/mediocregopher/radix/resp#Unmarshaler) into the `resp/resp2` package. The methods should be renamed to `MarshalRESP2` and `UnmarshalRESP2`.

* Create a new `resp/resp3` package. `resp3` will largely be a copy of `resp2`, but with additional RESP types added to it. `resp3` will have its own `Marshaler`/`Unmarshaler` interfaces, with `MarshalRESP3` and `UnmarshalRESP3` methods.

* Existing types in the main `radix` package will be modified to support all four interfaces.

* A new [DialOpt](https://godoc.org/github.com/mediocregopher/radix#DialOpt) should be created called `DialProtocol`, whose values can be `RESP2`, `RESP3IfSupported`, and `RESP3`. The default value will be `RESP3IfSupported`.

* The [radix.Conn](https://godoc.org/github.com/mediocregopher/radix#Conn) interface will need to be modified in some way so that `Encode`/`Decode` can accept either marshal/unmarshal interfaces, depending on the protocol of the underlying connection.

* Support for unmarshaling into big number and other decimal formats.

### Unknowns

* **Support for attributes:** Unmarshaling attributes may simply require an extra return value from `UnmarshalRESP3`, where that value is of type `resp3.Attributes`, which can be merged with other attributes. It would then be the responsibility of callers higher up the stack to consolidate the attributes of returned from multiple `UnmarshalRESP3` calls. There should definitely be support for dropping attributes and not wasting resources on them, which is the main unknown here. Should an options struct be added to the `UnmarshalRESP3` signature?

* `resp3.Any` may need to be modified so that the client is able to specify exactly which type they want some arbitrary data sent as. This specifier may need to be trickled down from `Cmd` in some way. Similarly, `Any` may want to capture the type of a RESP response.

* **Support for push messages:** Seems like this may need to be another return from `UnmarshalRESP3`, next to attributes.

## Maybe

The existing [MaybeNil](https://godoc.org/github.com/mediocregopher/radix#MaybeNil) type will be renamed to just `Maybe`, and will be augmented to also support empty responses of various sorts, for example `EmptyArray`, `EmptyMap`, `EmptySet`, etc...

## Run/Do

The existing naming around the `Run` and `Do` methods is not very good, both are quite generic and in the context of programming mean nearly the same thing. At least one of the methods, if not both, should be renamed. `Do` is most likely to remain the same; it's the one users are most likely to use and so brevity is better. `Run` could be renamed to `Perform` or `Act`, which would tie the method name to the subject (Action) better.

## EvalScript refactor

[EvalScript](https://godoc.org/github.com/mediocregopher/radix#EvalScript) could use a couple of modifications:

* A `FlatCmd` method.
* Offer a `Preload()` sort of method, and some kind of ability to only call the EVALSHA form, which would allow it to be pipelined. This might require a whole new type.

## MarshalRESP support for Any

Currently [Any](https://godoc.org/github.com/mediocregopher/radix/resp/resp2#Any) doesn't support marshaling `resp.Marshaler`s, due to how the `NumElems()` has to work for the purpose of creating array headers and flattening out objects. In effect there's no way for `Any` to know how many elements are about to come down the pipe without actually calling `MarshalRESP` and analyzing the result, which would be quite a burden. An alternate way to do this might be to add a `NumElems()` method on all `resp.Marshaler`s, so that each marshaler can determine its own number of elements ahead of time in a more efficient way.

## Context on Actions

It's been asked for and I have said it's not do-able, but it's worth revisiting. If it can be done in a sane way then it's absolutely worth doing. Note that this might involve getting rid of the `DialReadTimeout` and `DialWriteTimeout` options.

## Other

Some other random thoughts:

* [Cluster.NewScanner](https://godoc.org/github.com/mediocregopher/radix#Cluster.NewScanner) is ugly, the default `Scanner` should be able to deal with clusters implicitly.
* [PersistentPubSubWithOpts](https://godoc.org/github.com/mediocregopher/radix#PersistentPubSubWithOpts) should just go away.
* The trace package could use sprucing up.
* Make Cluster call `READONLY` on all connections by default.
* Perhaps move stub functionality into a testutils-style sub-package?
* Perhaps make [ClusterCanRetryAction](https://godoc.org/github.com/mediocregopher/radix#ClusterCanRetryAction) part of the Action interface.
* Expose internal errors from Sentinel.
* Expose internal errors from PersistentPubSub.
* Fix StreamEntry.Fields to be a `[]string` (#204)
* [Client-side caching](https://redis.io/topics/client-side-caching): might be worth explicitly supporting.

# Please Help!

If you have any other ideas/changes you'd like to see please comment and we'll see about getting them on this list.

(CC @nussjustin)

**Comment by nussjustin** [comment]
## RESP3 Support

Do you have any specific plans for supporting both RESP2 and RESP3 at once?

I thought about it for a bit, but couldn't come up with a simple, easy to use interface.

Since RESP3 is completly backwards compatible with RESP2¹ maybe we could just support RESP3.

¹ The only incompatibility that I can think of is the new `Null` type and `*-1` / `$-1`, but this can be handled transparently. For example in my [resp3 package](https://godoc.org/github.com/nussjustin/resp3), when checking the type of the next value, the package will automtically check for `*-1` and `$-1` and report them as `Null` and when trying to read a `Null` it will also accept the RESP2 null values.

### Unknowns

#### Support for attributes

If the handling of attributes and pushes is part of the `resp3.Unmarshaler`, that would mean every implementation would need to check for them manually (probably through a convenience function in the `resp3` package), which could easily be forgotten and adds a lot of code.

What about making this the job of the `Conn`? Before calling `UnmarshalRESP3` we can just check the next byte and if it's an attribute or a push, the Conn reads it and returns it as part of the `Decode` call. There are less `Conn` implementations so it's harder to forget and would keep the `resp3.Unmarshaler`s cleaner. We could then even add arguments to `UnmarshalRESP3` to allow ignoring these.

#### resp3.Any

RESP3 doesn't really change anything when sending data. Redis commands still use the same types as in RESP2 (an array + N bulk strings), so I don't think we need to change anything at all. This would be more useful for a server or proxy, but I think that's not something we should care about in radix (IMO something like my [resp3](https://godoc.org/github.com/nussjustin/resp3) package is more suited for these use cases, than a package like radix)

#### Support for push messages

See **Support for attributes**

Maybe we can just allow setting a channel on a `Client`/`Conn` which would then get all `Push` values, and if no channel is set we tell the `resp3.Unmarshaler` to skip the `Push` values.

This way a user could use a single goroutine for handling messages from multiple connections in a `Pool` or a `Cluster`. That could be useful with client-side caching.

## Run/Do

Agree. I'd prefer something like `Execute` (or just `Exec`) instead of `Run`, but that's not important.

## EvalScript refactor

Not being able to implicitly pipeline `EvalScript` is a bit annoying, since not using the (*cough* awesome *cough*) implicit pipelining means unnecessary overhead.

When writing a small data collecting service a few days ago, I had to manually work around this to improve the performance, which cost me a lot of time.

So having a `Preload` method or maybe a `EvalLoadedScript` type would be an important addition.

## Context on Actions

I'd love to see this for observability purposes.

IMO the `trace` package is currently mostly useful for background events (connection / pool / cluster / sentinel state changes), but not really useful for observing actual command execution (mainly because we don't even know which commands get executed).

## Other

* I am all for improving the `trace` package. If we extend the `Action` interface with a method for returning the command (#159), we could make the `trace` package a lot more useful, while at the same time allowing better direct observability (through e.g. a `Client` wrapper that uses `context.Context` together with something like Open Tracing or Prometheus).
* Making all `Cluster` connections `READONLY` would be nice, but that would need support from `Pool` itself. I'm not sure what'd be best way to do this, since users can specify custom functions for creating `Pool`s and `Conn`s.
* Support for client-side caching should be on our TODO list and I imagine this would work nicely with how I imagine **Support for push messages**.

**Comment by mediocregopher** [comment]
> Since RESP3 is completly backwards compatible with RESP2¹ maybe we could just support RESP3.

that's a good point, maybe it doesn't need to be so complicated. The custom Unmarshalers implemented in radix would still need to support both protocols within their UnmarshalRESP methods, but that's not much different than doing it across two different methods.

> What about making [attributes] the job of the Conn? 

How would the user go about actually accessing the attributes that have been collected in that case? For example if the user has a Pool and runs a Cmd on it, even if the underlying Conn is collecting the attributes they still need to bubble up to that Cmd's return in some way, I would think (I'm honestly not super clear on what use-cases attributes are going to come up in). If not for that I like the idea, you're right that it would simplify implementation a lot, and it seems to be what antirez intended based on reading the resp3 spec.

> RESP3 doesn't really change anything when sending data. Redis commands still use the same types as in RESP2 (an array + N bulk strings), so I don't think we need to change anything at all.

Ideally I would like radix's resp package to be useful outside of radix itself, but yeah if it becomes too onerous to do maybe it'd be better to reduce its scope to only being useful in the context of an actual redis client.

**Comment by nussjustin** [comment]
> How would the user go about actually accessing the attributes that have been collected in that case? For example if the user has a Pool and runs a Cmd on it, even if the underlying Conn is collecting the attributes they still need to bubble up to that Cmd's return in some way, I would think (I'm honestly not super clear on what use-cases attributes are going to come up in). If not for that I like the idea, you're right that it would simplify implementation a lot, and it seems to be what antirez intended based on reading the resp3 spec.

The `Client` could just return the attributes in `Do` or we may add a special struct similar to the `Maybe`/`MaybeNil` struct that would receive the attributes. Something like

```go
type WithAttributesBecauseNamingIsHard struct {
    AttributesRcv interface{} // or maybe just "Attributes resp3.Attribute"
    Rcv interface{}
}
```

The `Conn` could then check if the unmarshaler is of this type and either read the attributes into the `AttributesRcv` field. If the receiver is not of this type, we can just skip the attributes. Most users won't care about attributes, so this would avoid some overhead and won't force these users to change their `err := c.Do(...)` calls to `_, err := c.Do(...)`.

> Ideally I would like radix's resp package to be useful outside of radix itself, but yeah if it becomes too onerous to do maybe it'd be better to reduce its scope to only being useful in the context of an actual redis client.

That reminds me that RESP3 supports streamed aggregates (e.g. `*?\r\n`). So we wouldn't even need to know the array size if the server speaks RESP3, but we still need to support RESP2, so that won't work.

Instead of extending the `Marshaler` interface we could also just add a new interface `NumElemser` (master of naming strikes again) and fail for `Marshaler` values that don't implement this interface. Basically saying "you only need to implement this when your type should be usable with `resp.Any`".

**Comment by mediocregopher** [comment]
> Instead of extending the Marshaler interface we could also just add a new interface NumElemser (master of naming strikes again) and fail for Marshaler values that don't implement this interface. Basically saying "you only need to implement this when your type should be usable with resp.Any".

That could work 👍 

I started the v4 branch and began working on it. I had an idea I liked that I started implementing: rather than `Conn` having both `Encode` and `Decode` methods, I consolidated them into a single `EncodeDecode` method. There's a couple of consequences of doing this:

* Implicit pipelining could occur on the Conn level, rather than Pool (not yet implemented).

* Things like EvalScript can become pipeline-able (implemented).

* We might be able to do away with CmdAction entirely (WIP)

So far most of the code hasn't changed too much because of it, but I haven't yet moved implicit pipelining onto Conn (nor decided if that's actually a good idea, or what it would look like from a configuration perspective).

**Comment by nussjustin** [comment]
> Implicit pipelining could occur on the Conn level, rather than Pool (not yet implemented).

One advantage of having implicit pipelining on the Pool is that the implicit pipelines are larger. If we have implicit pipelining on the Conn itself the pipelines would be smaller since a Pool would always add commands to a random Conn. While this wouldn't make much of a difference for the client (I believe), this would result in higher CPU usage on the server.

Working around this by trying to execute commands on a single Conn in a Pool (similar to how it works now) would also not work since the Pool wouldn't know when the Conn gets flushed.

Not sure how much this would really affect the performance and CPU usage (especially with IO Threads in Redis 6, or even fully multi threaded Redis forks like KeyDB).

I'd say we should benchmark this and also take a look at the Redis CPU usage. Maybe even have multiple Pools to the same Redis, all with their own implicit pipelining. This way we can observe the effects of having multiple apps connected to Redis on how they affect each other, especially latency wise. Until know we only tested with a single app connected to Redis.

This way we could measure how small and big pipelines affect other clients as well. For example using big pipelines, like we do now with the Pool level implicit pipelining, means that Redis could be blocked relatively long, which increases latency for other connected clients (e.g. other instances of the same program).

Also I saw the comment about moving implicit pipelining into connWrap. Shouldn't it be possible to have implicit pipelining just be a wrapper around a Conn? This way disabling implicit pipelining could be done by just not wrapping the Conn. It would also probably me much cleaner.

> We might be able to do away with CmdAction entirely (WIP)

_Excellent_...

**Comment by mediocregopher** [comment]
I guess I was a bit hasty with the "Implicit pipelining could occur on the Conn level" comment. EncodeDecode doesn't actually open that door anyway, we could do that now by making pipeliner public (I think...), we just didn't because the API was already crazy enough. If we're getting rid of CmdAction though then maybe we could trade that for a public implicit pipelining wrapper for Conn, like you mentioned, which Pool could then use in the same way it's currently using pipeliner.

I'm certainly all for benchmarking, but my biggest priority is to have everything be configurable by the user in an obvious way. Once that's done we can break out the benchmarks to figure out a set of defaults that works well for the most common use-case. So for now I'm going to keep playing with the API and see how implicit pipelining best fits in it, and see what else can be reduced away.

**Comment by mediocregopher** [comment]
Other thoughts which have occurred to me as I've been using the package:

* `RawMessage.UnmarshalInto` is a convenience method, it might as well take an `interface{}` like `Cmd` and `FlatCmd` do.
* StreamReader could do more. Right now it works well but is a bit bare-bones. Creating the stream/group, dealing with pending messages, acking...
* Exposing the unmarshaler which can parse the results from XREAD and XREADGROUP (this could be done for v3 too)
* `PubSub` should be renamed to `NewPubSubConn`, `PersistentPubSub` should be renamed to `NewPersistentPubSubConn`.

**Comment by mediocregopher** [comment]
Update: Just pushed a big set of changes to the `v4` branch, notably:

* Implemented a public `NewPipeliningConn` function. For now I've taken out implicit pipelining completely, with the idea that if it's desired someone can make two pools, one for pipelining conns and one for vanilla conns, and direct their actions appropriately. This makes the whole library more future-compatible and reduces weird edge-cases which weren't handled before (like a lua script which calls BZPOP or something like that).

* Removed `CmdAction` completely.

* Refactored `Pipeline` significantly, so that it can be used both for itself and the pipelining conn.

* Renamed `ErrDiscarded` to `ErrConnUsable`, and had it be used for some marshaling errors as well.

**Comment by creker** [comment]
How about some helper methods to execute commands on every node of Redis cluster? go-redis has a couple of useful methods for this
```go
func (*ClusterClient) ForEachMaster
func (*ClusterClient) ForEachShard
func (*ClusterClient) ForEachSlave
```
I'm most interested in something like ForEachMaster. I know it's probably not okay to do that kind of thing in production but it's very useful in tests where I want to flush data on all nodes or do some other cluster wide operation.

**Comment by nussjustin** [comment]
@creker These could easily be added after 4.0, since they don't break the API. This issue is more about breaking changes :-)

**Comment by creker** [comment]
@nussjustin ah, sorry. 

Yes, ForEachMaster could be added later. But I think EvalScript needs different API. I don't know if you're willing to break it completely or just add alternative method with better API and leave the existing one for compatibility. Just wanted to throw it out there since you're discussing next major release. Radix is awesome for its speed but API is a bit clunky in places.

**Comment by mediocregopher** [comment]
Hi @creker thanks for the suggestions!

> Another idea is to allow EvalScript to accept variable number of keys. It's very limiting right now to specify the number of keys upfront.

Are you thinking that the number of keys would be passed in as an argument to `Cmd` rather than `NewEvalScript`? I can't think of any reason why that wouldn't be do-able....

> Radix is awesome for its speed but API is a bit clunky in places.

We're hoping to make both the speed and the API awesome :) what other parts of the API do you find clunky?

**Comment by creker** [comment]
> Are you thinking that the number of keys would be passed in as an argument to Cmd rather than NewEvalScript?

Yeah, something like that. I found it very weird that I had to specify the number of keys upfront. Luckily for now it's not that pressing, I can just create several scripts with needed number of arguments. In the end I even ditched the EvalScript altogether in favor of manual preloading and EVALSHA. Probably similar to what you described earlier.

> We're hoping to make both the speed and the API awesome :) what other parts of the API do you find clunky?

Not many. The one that bothers me the most is working with sorted lists. In particular when you need both members and their scores. Maybe I'm missing something but I couldn't find a way to make it work with structs. For example, I tried this kind of struct

```go
type Z struct {
    Member string
    Score float64
}
```

No matter how I passed it, in ZRANGE WITHSCORES or ZADD, I couldn't make it work. In other places Radix is quite good at marshaling/unmarshaling stuff for you via reflection. But here I was forced to use []string arrays where both member and scores are in string form. It's a couple lines of code but would be great if Radix could somehow deal with it. Not sure how exactly - magically figure out how to marshal/unmarshal structs on its own in this specific case, use special struct tags or even provide ready to use type like Z above. Lot's of ways to do it.

Second thing affects both pipelines and EvalScript but looks like it's already fixed  - support for implicit pipelining.

**Comment by mediocregopher** [comment]
I've implemented resp3 support, after a _lot_ of spinning my wheels writing a crazy amount of tests. But now I feel a lot more confident in that code than I do in the resp2 code. I left the resp2 code in there for now, I haven't decided if it should stay or go yet. It's not necessary for radix to function, but if someone is writing something custom which uses it directly they may want to be able to use resp2 specific stuff (like null bulk strings/arrays).

**Comment by mediocregopher** [comment]
I spent the evening doing a bit of prioritization and culling of pending v4 features. I came up with this set:

# V3+V4

Changes which will also happen on v3 take highest priority.

* Add a helper receiver for EXEC results.
* Expose the unmarshaler which parses XREAD and XREADGROUP results.
* FlatCmd method on EvalScript.
* Expose internal errors from Sentinel.

# V4 backwards incompatible

Next highest priority are changes which break backwards compatibility. These are required for v4 to be declared "public".

* MaybeNil -> Maybe
* Make Actions take context
* Factor out Cluster.NewScanner
* Spruce up trace package, try to address #159
* Cluster READONLY on all connections
* Move stubs into testutils?
* Factor out ClusterCanRetryAction?
* Expose internal errors from PersistentPubSub
* Fix StreamEntry.Fields to be a []string (#204)
* Figure out how PipeliningConn will work with Pool.
* Make RawMessage.UnmarshalInto take an interface{}.
* Expand StreamReader's scope, it could be handling pending messages as well.
* Rename PubSub -> NewPubSub, PersistentPubSub -> NewPersistentPubSub
* Pass number of keys into (Flat)Cmd method of EvalScript
* Some kind of flattening on unmarshaling side? E.g. unmarshaling an array into [][2]string.

# V4 Eventually

These can be done after v4 is released, but won't be backported to v3

* DialProtocol - DialOpt which informs which protocol is used on a connection.
* Conn wrapper which intercepts Push messages and writes them to a channel.

**Comment by mediocregopher** [comment]
Work on v4 is going well, I'm aiming to wrap up around new years. @nussjustin I completely rewrote Conn and Pool. Conn is now thread-safe and will do implicit pipelining (which I'm renaming to connection sharing because that's less confusing) automatically. The Pool will properly handle Actions based on whether or not they're shareable. If an Action is shareable the Pool will pick a random available Conn and perform the Action against it. If the Action is not shareable then the Pool will first make a Conn unavailable for other Actions before performing the given one. So we get the benefits of implicit pipelining.... implicitly :D Also Pipeline and EvalScript are shareable now as well :raised_hands: 

(There's a slight potential regression in that Pool no longer prioritizes sharing all to a single connection like in v3, so we're potentially incurring more system calls for the same workload. I have yet to run benchmarks to see what the practical effect of this is, but in any case it's something that I think can be addressed after release, if desired.)

The new Pool also does away with the previous one's behavior of on-demand connection creation when the pool is empty. Because all Conns will be shared for the vast majority of Actions it should be very rare that the Pool actually runs out of Conns, except during error cases (which are handled in the new Pool by a reconnect go-routine).

**Comment by mediocregopher** [comment]
Alright, v4 open beta is officially launched!

Changelog: https://github.com/mediocregopher/radix/blob/v4/CHANGELOG.md
Docs: https://pkg.go.dev/github.com/mediocregopher/radix/v4#section-documentation

The branch is still tagged as beta, so it's not too late for breaking changes, but at this point I'm done with the bulk of the improvements I'd like to make, and am going to close this issue. If you're reading this and have any suggestions/problems, please open a new issue. I'll be doing benchmarks in the next few days as well.
