### ISSUE TITLE
Unknown key for WithConn transaction

### ISSUE THREAD

**Issue by gabriel-vasile** [mediocregopher/radix#214]
Hi!

I'm using the library by creating transactions with MULTI/EXEC inside `WithConn` just like in the [example](https://godoc.org/github.com/mediocregopher/radix#example-WithConn--Transaction).
My problem is that I do not know upfront any keys the transaction is going to work on.

What is going to happen if I use the empty string as the key? What if I pass a key which is not going to be acted upon inside the transaction?

I guess `WithConn` docs could mention what happens in these cases.

**Comment by mediocregopher** [comment]
Hello @gabriel-vasile! if you're not using Cluster then it doesn't actually matter what value you pass as the key. The key is only necessary so that Cluster is able to give you a connection for the proper instance in the cluster. So most likely you don't need to worry about it. If you _are_ using Cluster then you may need to rethink your application design a bit.

I'll clarify the docs a bit though.

**Comment by mediocregopher** [comment]
Fixed by 626b761.

If you have any further questions feel free to reopen the issue :) Thanks!

**Comment by gabriel-vasile** [comment]
Great! I'm not using a cluster. Thank you!
