### ISSUE TITLE
Panic in Do when cluster has a node in the `LOADING` state

### ISSUE THREAD

**Issue by effward** [mediocregopher/radix#216]
Thanks for writing this redis client, it's been awesome to work with and has been generally working really well.

Sometimes when the redis cluster is having a lot of failover events (and some nodes seem to spend a long time in the `LOADING` state) we are seeing the following panic occur.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc55eff]
goroutine 491272 [running]:
github.com/mediocregopher/radix/v3.(*Cluster).addrForKey(0x0, 0xc000725868, 0x7, 0x0, 0x0)
	/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.5.1/cluster.go:468 +0x9f
github.com/mediocregopher/radix/v3.(*Cluster).Do(0x0, 0xfc20e0, 0xc000a3f380, 0x16, 0xc0008ecb00)
	/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.5.1/cluster.go:528 +0x120
```

When our service gets an updated list of redis endpoints (due to failovers), we attempt to call `cluster.Sync()`. If that fails more than a couple of times, we then try to create a new cluster and close the old cluster (to cover the case when every endpoint has changed). Perhaps there is a better way to handle this?

Let me know if there is any additional info I can provide.

**Comment by mediocregopher** [comment]
Hi @effward , thanks for the kind words :) The line which appears to be panicking is doing `c.l.RLock()`. The only way that could be panicking is if the `*Cluster` receiver variable is nil. Since that's being called within `Do` I think what's happening is you must be calling `Do` on a nil `Cluster`.

> Perhaps there is a better way to handle this?

I don't think it should be necessary to call `Close` and remake the `Cluster`. The only time it _might_ be necessary to do that is if all redis instances go down completely, and a whole new cluster is brought up on different IPs (in effect, a whole new cluster). But that's something you'd have to do deliberately, it's not a normal failure case. I think calling `Sync` periodically is fine, as long as at least one of the redis instances which Cluster knows about is online it should be able to recover just from that.

**Comment by effward** [comment]
It does seem like that is probably the cause. I haven't yet found how that can happen in our code, but will take a look tomorrow when I have some time.

Thanks for your timely response.

**Comment by effward** [comment]
Found the issue, thanks for pointing me in the right direction.
