### ISSUE TITLE
Unexpected pooling behaviour

### ISSUE THREAD

**Issue by creker** [mediocregopher/radix#219]
Looks like I hit the same problem as in #37 

The other day our redis cluster was having problems causing commands to go slow or even some instances completely lock up. At the same time the app that used radix was hit by a large amount of concurrent requests. This caused radix go haywire and start to open thousands of connections completely exhausting the available limit on the redis side. It got to a 20k connections completely starving anyone else. That's not ok so I experimented a bit.

I built a program that emulates slow Redis handling large amount of concurrent requests
```go
redis, _ := radix.NewCluster("127.0.0.1:6379")
for {
	var wg sync.WaitGroup
	for i := 0; i < 2000; i++ {
		wg.Add(1)
		go func() {
			if err := redis.Do(radix.Cmd(nil, "BLPOP", "test", "1")); err != nil {
				panic(err)
			}
			wg.Done()
		}()
	}
	wg.Wait()
}
```

This code causes radix to open thousands of connections to then immediately close them. Setting the limit to anything more than 2000 exhausts all available ports on my machine. Our app is distributed and can open much more connections as a whole. Looks the problem is reproduced.

I started to look at why radix was doing this and how it can be fixed. First I looked at the default pool settings and found `PoolOnFullBuffer((size/3)+1, 1*time.Second)`. Ok, some overflow buffer in case all connections are exhausted is ok but I don't really understand the implementation. As I understand it, it should specify an upper limit on the amount of connections that radix opens. But that's not the case. Radix will keep opening connections until it exhausts all available resources completely ignoring overflow limit. I don't think that the correct behavior.

Then I found `PoolOnEmptyWait` which fixes the problem. New connection are no longer being opened even if new requests are keep coming. But the problem is it doesn't interact properly with `PoolOnFullBuffer`. I would think that the latter would still allow connections to overflow a bit and only then would radix completely lock up until a connection becomes available. But in reality `PoolOnFullBuffer` is completely ignored. I can set it to 1 or 1000 but the amount of connections opened stays the same and is equal to the size of the pool.

So something isn't right here. The interaction between `PoolOnEmptyWait` and `PoolOnFullBuffer` doesn't seem correct and probably should be fixed or at list documented as a limitation. `PoolOnFullBuffer` behavior is unexpected. Either it should be fixed or another option should be introduced that actually puts a hard limit on the amount of connections radix can open in any circumstances. Something like Go's http.Transport.MaxConnsPerHost which puts a hard limit on the amount of concurrent http requests by hard limiting the amount of opened connections. Setting it to 0 causes the same problem as with radix - connections are being opened until ports are exhausted.

**Comment by mediocregopher** [comment]
Hi @creker , thanks for diving into this so much! Hopefully we can get it fixed.

> I would think that the latter would still allow connections to overflow a bit and only then would radix completely lock up until a connection becomes available.

I agree with that, the fact that it doesn't seems like a bug to me. I'll investigate and try to come up with a fix.

**Comment by mediocregopher** [comment]
Ok so actually I may have spoke too soon. if `PoolOnEmptyWait` is set then there's no occasion where the pool will create new connections (save for the refill event, but that doesn't come into play here because connections aren't being closed). So therefore there's no way for more connections than the pool size to be created, and the overflow won't be used. I'm not sure there's a good way to reconcile this, it might just have to be a documented design flaw that we can try to resolve in v4.

**Comment by creker** [comment]
Then it's probably best to wait for v4. In v4 we can change behaviour to allow `PoolOnFullBuffer` to overflow while `PoolOnEmptyWait` or `PoolOnEmptyErrAfter` will keep pool from growing above the overflow limit. That way radix will have some slack to handle traffic spikes but still be hard limited on the amount of connections it can open. Right now I solved my problem with `PoolOnEmptyErrAfter`.

**Comment by mediocregopher** [comment]
@creker v4 is officially in public beta, so feel free to check it out. The `Pool` has been completely rewritten, but I'm thinking you might find it to be a step backwards, so I wanted to explain what I did and see what you think.

v4 has a new `Conn` implementation which supports parallel command execution on the same `Conn`. In v3 we called this "implicit pipelining", in v4 I'm calling it "connection sharing", but it's essentially the same thing. The new `Conn` supports connection sharing for almost all Actions, whereas v3 only did on a small subset.

What this means for `Pool` is that the vast majority of the time it's not necessary to "remove" a `Conn` from the connection pool to use it, it can just be used in-place alongside other concurrent actions which can use the same `Conn` as well. The only times a `Conn` would be removed from the `Pool` is if a blocking command (e.g. BRPOP) is being performed, or for something like `WithConn`.

With that in mind, the new `Pool` is statically sized. It has a fixed number of `Conns` and it attempts to maintain that specific number throughout runtime. There's no growth of the pool during high load, because it's not clear how to even determine when load is particularly high.

What do you think? There's still room to allow for connection pool growth in the API, so that can be added in later if needed and if there's a reasonable metric on which to do so.

**Comment by creker** [comment]
@mediocregopher will definitely check it out, thanks.

The way you describe it sounds reasonable. My problem was with uncontrollable growth of opened connections, so it looks like it will no longer be a problem. I don't really need it grow dynamically. Fixed number of connections is completely fine.

As for new approach, I see you removed pipeliner but I don't really understand how it achieves the same effect now. I see that there's something called WriteFlushInterval which is 0 by default (there's also TODO in benchmarks). The way it's used in conn_writer.go looks similar to pipeliner. Is it? And does it mean that now we need to specify WriteFlushInterval in dialer ourselves in order to achieve the same effect as before? I understand that manual pipelining is much faster now but implicit pipelining is still very cool feature. Maybe that's why v4 in some cases is slower than v3.

**Comment by mediocregopher** [comment]
Implicit pipelining is still used, but it's being called connection sharing now since that describes what's happening better. Each Conn can have concurrent commands being performed against it, the writes and reads for these are pipelined under the hood. So implicit pipelining is still there, _and_ manual pipelining is now better because it works correctly with the implicit pipelining.

As for WriteFlushInterval, I'm still not sure exactly what to do with that. By setting it to ~100us you can increase the effectiveness of the connection sharing, but it's not required to set it for connection sharing to work. I may have PoolConfig automatically set WriteFlushInterval in certain cases, but I didn't want to do it quite yet.

**Comment by mediocregopher** [comment]
@creker do you have any other questions/concerns about shared connections? If not I'd like to close this issue
