### ISSUE TITLE
ERR wrong number of arguments for 'auth' command

### ISSUE THREAD

**Issue by gadelkareem** [mediocregopher/radix#222]
I am trying to connect to Heroku Redis service using this radix but I am getting this error 
```
ERR wrong number of arguments for 'auth' command
```
Redis URL looks like `redis://u:somelongpassword@ec2-23-230-76-1.compute-1.amazonaws.com:22349`

I logged into the server using `redis-cli -u redis://u:somelongpassword@ec2-23-230-76-1.compute-1.amazonaws.com:22349` without a problem.

Anyway to debug this?

**Comment by gadelkareem** [comment]
Oh it requires an empty username `redis://:somelongpassword@ec2-23-230-76-1.compute-1.amazonaws.com:22349`? I think it should be handled by the library to ignore the username, why do you send an error?

**Comment by nussjustin** [comment]
Redis 6 has added support for ACLs and multiple users. To support this radix will automatically use the "new" `AUTH` syntax (`AUTH <username> <password>`) when a username is specified, unless the username is `default` or empty in which case the "old" `AUTH` syntax is used (`AUTH <username>`).

**Comment by gadelkareem** [comment]
Understood, thanks for clarification. Do you know why `redis-cli` is not failing?

**Comment by nussjustin** [comment]
I guess that the redis-cli probably checks the Redis version and then does the `AUTH` based on the version or just tries both.

**Comment by gadelkareem** [comment]
hmm.. Can I request this feature form radix? 😊

**Comment by nussjustin** [comment]
I don't think this would make sense to implement. It would only break people upgrading to Redis 6 and slow down connection initialization just so that an URL can contain some random user name that has no meaning and would be ignored.

**Comment by mediocregopher** [comment]
Sorry @gadelkareem, I agree with justin. This seems like an edge-case, and I'd rather not add extra round-trips to dialing unless it's absolutely necessary. This is something you could support yourself by implementing a custom conn func, or just don't pass in a username if the server doesn't support usernames.

**Comment by gadelkareem** [comment]
Thanks @nussjustin and @mediocregopher 
It is understood that such a feature is a low priority of course. Although for the sake the argument, it would not slow down the connection since you will probably save a flag for the auth type as soon as you parse the URL so no need to re-parse for each connection.

Please feel free to close it or label it as low priority...

**Comment by nussjustin** [comment]
Looking at the URL is not enough to determine which `AUTH` syntax to use. The `Conn` would either need to try both syntaxes or check the Redis Version (via `INFO`, which may not always work because of ACLs and Aliases) or the `AUTH` command meta information (via `COMMAND`, which also may not always work for the same reasons as for `INFO`). In both cases there would be additional latency (though in the first case it would only be in case the first `AUTH` fails).

Also since the authentication is done on the `Conn` level, the determined syntax can't be cached for future `Conn`s. So when creating multiple `Conn`s, e.g. in a `Pool`, every `Conn` would incur the overhead.

Plus there is no guarantee the Redis version always stays the same for one URL (you may upgrade or downgrade Redis without restarting the application in which case the application should just reconnect).

And again, this would break applications when you upgrade to Redis 6 without adding a new user with the username your application uses, since radix would then automatically start using the new `AUTH` syntax which would fail in this case.
