### ISSUE TITLE
I need help preserving the connection pool

### ISSUE THREAD

**Issue by ianidi** [mediocregopher/radix#225]
Hi,
I apologise I need some help with dumb question.

I have a connection function which returns a radix pool.

```
package redis

func InitRedis() *radix.Pool {
	DefaultConnFunc := func(network, addr string) (radix.Conn, error) {
		return radix.Dial(network, addr,
			radix.DialTimeout(10*time.Second),
			radix.DialAuthPass(viper.GetString("redis_password")),
		)
	}

	var err error
	client, err := radix.NewPool("tcp", viper.GetString("redis_host"), 10, radix.PoolConnFunc(DefaultConnFunc))
	if err != nil {
		panic(err)
	}
	return client
}
```

How should I use it to make this pool global in my golang project? I would like to create it **just once** and use this connection in any file of my project.

E.g. 
```
func GetRedis() *radix.Pool {

	...

	return client
}
```

I've put this in my main.go 
```
	radix := redis.InitRedis()
	defer radix.Close()
```

Still not sure if I'm moving in right direction.

**Comment by mediocregopher** [comment]
Hello @ianidi , I'll try to help as best I can. The first thing I'll say is that I don't generally advise using a global pool throughout an entire app. Imo It's better to pass the Pool into each component which needs it in the component's constructor. This way you're able to better configure the pool for each individual component which needs one. For example, multiple components may share the same pool, while some other component gets its own because it tends to have usage spikes which you don't want to effect the other components. Or perhaps one component wants to use different timeout values.

To actually answer your question, I think having an `InitRedis` in main and then using `GetRedis` throughout the app works just fine. The change I would make would be for `InitRedis` to not return its pool, but rather to assign it to a global variable, and then `GetRedis` would simply return that global value. `GetRedis` could also check to make sure the global value is actually set and panic if not, so it's clear when you've forgotten to call `InitRedis`.

Hope this helps!
