### ISSUE TITLE
Pipelining in cluster mode

### ISSUE THREAD

**Issue by mdubbyap** [mediocregopher/radix#228]
I think i'm misunderstanding or just not finding the correct documentation, but trying to work with a redis cluster and do either an mget or pipelined gets. 

I see ClusterSlot, but i would have to maintain and update a slot list myself and don't really want to do this as it feels like the client should do it (and already is).

So, i figured pipelined gets should work, but they too fail with as pipelines keys are checked for the same thing as an mget is. I'm a little stumped as to how this is supposed to work. Any help would be appreciated. Thanks.

**Comment by mdubbyap** [comment]
Moreover, i think the logic inside of radix.assertKeysSlot() is just wrong. It's asserting that they must be exactly the same key slot, not the same keyspace the node is handling. 

It's a shame, i really prefer the interface on this client, but it doesn't appear that cluster mode is working for anything but simple or non pipelined commands.

**Comment by nussjustin** [comment]
You are right that there is no support for splitting up pipelines for clusters. But that could be implemented pretty easily by splitting up the pipelines.

One problem is that this could quickly lead to bad performance (or even worse, unpredictable performance). Another one is that you can't guarantee the order of commands which could be important.

Support this for normal non-pipelined commands would mean hardcoding special logic for some commands which can quickly get more confusing then helpful (why does it support command X but not Y? why not all commands?).

There is also an official cluster proxy that supports what you want by completely abstracting away a cluster: https://github.com/RedisLabs/redis-cluster-proxy

> Moreover, i think the logic inside of radix.assertKeysSlot() is just wrong. It's asserting that they must be exactly the same key slot, not the same keyspace the node is handling.

I think multiple keys mapping to different slots are not allowed in a single command on a Cluster, but I could be wrong about this. At least there is no way a moving slot could be handled correctly with multiple different slots in a command.

**Comment by mediocregopher** [comment]
> I think multiple keys mapping to different slots are not allowed in a single command on a Cluster

This is true for transactions, a single pipeline of independent commands would work, but yeah it's not something that's reliable due to migrations like you said. @mdubbyap if you feel like you're ok with that risk then it's easy enough to wrap Pipeline's Keys method to only return a single one of the keys involved.

As for MGET, this couldn't be implemented in the normal `Cmd` because that would be too much magic. It _could_ be implemented as a new and separate action, but I never felt like implementing or supporting it. If you'd like to see it as part of this project I'd happily review an MR :)

As for implementation, radix exposes all the tools necessary: you can use the `Topo` method to get the current cluster topology, collect the commands based on `ClusterSlot`, then execute the pipelines in parallel on the cluster (using the wrapped pipeline to trick Cluster into letting it happen). Figuring out what to do when there's ongoing migrations is where it gets complicated....
