### ISSUE TITLE
Redis cluster cpu soars to 50%, which takes several seconds

### ISSUE THREAD

**Issue by kataras** [mediocregopher/radix#232]
Hello @mediocregopher, how are you?

An Iris user reported a case which result in slow operation on cluster (and I think in stand alone mode too) with radix library. Please read it through: https://github.com/kataras/iris/issues/1610, is an Iris issue about how is using the radix library or is it bug/feature request of this radix library? Please don't hesitate to comment on that issue and ask for more information from the end-developer.

Thanks,
Gerasimos Maropoulos

**Comment by mediocregopher** [comment]
Hi @kataras , I hope you're well. it looks like maybe the original issue has already been resolved, but from what I can tell the issue stems from a SCAN being done on a multi-million key redis cluster. From what I can tell the original user is suggesting to use a hash rather than a set of keys which must be SCAN'd over, which I agree with greatly. An important thing to note about SCAN is that even if you give it a MATCH argument it will still iterate over every key in the redis instance/cluster, it just will only return those which match the pattern. Ultimately I believe this is an issue with how redis is being used and not the driver itself.
