### ISSUE TITLE
Stub converts strings to []byte inside the array of empty interfaces during the marshalling.

### ISSUE THREAD

**Issue by santriseus** [mediocregopher/radix#248]
Hi, not sure if it is the issue, or expected behavior.
I want to mock some complex commands like https://oss.redislabs.com/redisearch/Commands/#ftinfo using the Stub function.
I noticed, that if I try to return from Stub
```
[]interface{}{"key1", "value1", "key2", []interface{}{"some_key"}, ...}
```
all the strings will be converted to []byte. At the same time, I could see that when running the real radix commands, at least keys remain the string type. Is it possible to achieve the same behavior using the stub?
Link for a commit with a failing test: https://github.com/santriseus/radix/commit/9ab0f0d1b2609891b4f6e13b75f394d230c7fced

**Comment by mediocregopher** [comment]
Hi @santriseus! It's great to know that someone is actually using Stub, that's honestly not something I expected :)

As for your question, the behavior you're seeing is expected. What's happening is this:

* Stub is marshaling `[]interface{}{"string", "value"}` into its RESP representation via `resp2.Any`. This is roughly what `FlatCmd` does as well. `string` will be marshaled as a RESP bulk string, so `[]interface{}{"string", "value"}` will be marshaled as an array of two bulk strings.
* The RESP message obtained in the previous step is then unmarshaled into your receiver value of `Cmd`, which is of type `[]interface{}`. Since you're not specifying the type of the interior interface radix picks one. For bulk string messages radix picks `[]byte`. So your `[]interface{}` gets filled with two `[]byte` values.

> I could see that when running the real radix commands, at least keys remain the string type.

I'm guessing what's happening is that the `ft.info` command is returning RESP simple strings for the keys, rather than bulk strings. When unmarshaling a simple string into a `interface{}` radix will pick the `string` type.

If you'd like to return a simple string from Stub you can use the `resp2.SimpleString` type directly:

```
		case "COMPLEX":
			return []interface{}{resp2.SimpleString{S: "string"}, "value"}
```

For the receiver type I recommend checking out struct unmarshaling, it's described in the package docs. For that complex type you could do something like:

```
type IndexDef struct {
	KeyType  string   `redis:"key_type"`
	Prefixes []string `redis:"prefixes"`
	Filter   string   `redis:"filter"`
	// etc...
}

type FTInfoRes struct {
	IndexName       string   `redis:"index_name"`
	IndexOptions    []string `redis:"index_options"`
	IndexDefinition IndexDef `redis:"index_definition"`
	// etc...
}

var res FTInfoRes
err := client.Do(radix.Cmd(&res, "ft.info", "wik{0}"))
```

The rules for struct marshaling/unmarshaling try to follow that of the `encoding/json` package as closely as possible.

Of course if you want to use `[]interface{}` you're more than welcome to as well, just giving you options :)

**Comment by santriseus** [comment]
@mediocregopher Thanks, unfortunately `resp2.SimpleString{S: "string"}` is unmarshaled to `[]interface{[]bytes, []bytes,}` where the first one is "S" and the second one is "string". (Probably because it is structure and structures are marshaled to key-value arrays).
For sure I will try fancy struct marshaling, but I wanted to cover with tests some legacy before the refactoring.

**Comment by mediocregopher** [comment]
@santriseus sorry it took so long to get back to you, it's been a busy year. I did some investigating and realized my original message to you wasn't correct. radix v3's `resp2.Any` type is not able to marshal `resp.Marshaler`s correctly (including `SimpleString`) due to the way it was designed. It's an unfortunate design hole in the app but at this point I don't believe it's able to be solved.

Fwiw radix v4 does _not_ have this design hole, and your test case works fine in it. I added a case just now in commit 0c666a8. I'm sorry I'm not able to fully help you in this, but I hope you've been able to make do in the meantime anyway.
