### ISSUE TITLE
cluster not support do pipeline

### ISSUE THREAD

**Issue by orange-jacky** [mediocregopher/radix#259]
i use radix.v3 and radix.v4 package. and find that redis  cluster do  pipeline fail, keys "xxx" and "yyy" do not belong to the same slot, how to support it

**Comment by mediocregopher** [comment]
Hi @orange-jacky , that error is due to keys being used in your pipeline not belonging to the same cluster slot. If you're certain that all keys in your commands belong to the same cluster node (which is _not_ the same as the same slot) then you can wrap Pipeline in an outer Action which overrides the Keys (v3) or Properties (v4) method and returns a modified set of keys. But this isn't recommended as your code then won't behave properly during key migrations.

**Comment by orange-jacky** [comment]
could radix support auto wrap pipeline for keys belong to different cluster slot?

**Comment by mediocregopher** [comment]
@orange-jacky I do not have any plans to do add this as builtin functionality, because I do not personally think it's a good idea to do. If you want to do it it's easy enough to implement it within your application.
