### ISSUE TITLE
client and server run same host, and client connnect server fail

### ISSUE THREAD

**Issue by orange-jacky** [mediocregopher/radix#264]
on 172.29.8.49 , i telnet connent 5000, it works

telnet 172.29.8.49 5000
Trying 172.29.8.49...
Connected to 172.29.8.49.
Escape character is '^]'.

on 172.29.8.49 , redis  connent 5000, it not work
redis_client.go:67: error creating client for "172.29.8.49:5000": dial tcp 172.29.8.49:5000: connect: no route to host

how to fix it?

**Comment by mediocregopher** [comment]
@orange-jacky i'm afraid this is an issue with your networking, not with radix. `no route to host` is returned by the OS if it doesn't know how to contact a particular IP address or if that host is not able to be contacted. Perhaps there's some firewall rule that you're hitting? In any case I'm going to close this because I don't believe it's an issue with radix.
