### ISSUE TITLE
v4: Incorrect data returned by shared connection in presence of errors

### ISSUE THREAD

**Issue by apersson** [mediocregopher/radix#277]
Requests sent over a shared connection in a connection pool can return incorrect data if earlier requests experienced errors (e.g., timeouts)

If a request in `conn.reader()` returns before consuming its response from the receive buffer, then the buffer is left in an inconsistent state. While the connection is eventually closed due to the error, there can be in-flight requests that are processed before then, and the responses for those requests will be read from the now inconsistent receive buffer.

For example, if there are 3 connMarshalerUnmarshaler's (R1, R2, R3) in rCh and the context for R1 has timed out. R1 sees an error right away and the receive buffer is untouched. R2 follows and reads the buffer and consumes R1's response, and R3 would get R2's response.

Similarly, on the write-path, if a write failed, then the receive buffer can also get into an inconsistent state as it's not known how much of the buffer was successfully flushed and which responses will be received.

**Comment by nussjustin** [comment]
If a write fails, all other writes have to be either canceled or executed on another connection.

If we separated marshaling from writing to the connection (e.g. by first marshaling to an in memory buffer) we could skip commands that failed to marshal and only cancel the other commands when we got an error from writing. This would be a small hit to performance if we do this on the writer goroutine because of the copying but should not be too noticeable (and theoretically we could even do this before sending the action to the write channel, thus potentially even reducing the time needed for marshaling since all commands would be marshaled concurrently, but that would be a more complicated).

The reader part is similar to #274, but unlike #274 this is also about what happens when we timeout / get an error before even reading from the connection.

For reads the only thing we can do is to read and discard the response that would have been unmarshaled after sending the previous error to the goroutine that executed the command. This could mean waiting a long time but I don't see any other way to handle this.

**Comment by apersson** [comment]
Thanks for the quick response, @nussjustin. I've linked in a potential fix.

**Comment by mediocregopher** [comment]
Thank you both @apersson and @nussjustin for looking into this. I think the solution to this problem will be related and dependent on the solution to #274, so I'd like to resolve that before diving into this one.

**Comment by mediocregopher** [comment]
@apersson can you retest now that #274's PR is merged? I believe it should address this issue.

**Comment by apersson** [comment]
@mediocregopher, it resolved it for the test application I used to reproduce the issue. We are still seeing data mismatches in the context of larger application -- but that could be on our side. I'll file a new issue if I'm able to trace something back to radix.

**Comment by apersson** [comment]
And thanks for the quick fix.

**Comment by apersson** [comment]
@mediocregopher, it looks like the fix improved the situation significantly (about a 90% reduction), but there are still situations where we catch reordered data from the client.

**Comment by mediocregopher** [comment]
@apersson are there any further details you can give about your case? Are you using Pool? What kinds of commands are you doing? Are you seeing any errors occur before or after the out-of-order data is received? A test case reproducing the bug would be very helpful as well, if that's possible.

**Comment by apersson** [comment]
@mediocregopher, we are using a Pool and the commands (EVALSHAs and MGETs) go over the shared connection. It does seem to be triggered after errors -- from our logs I'm only seeing receive timeouts, with a majority of them hitting "waiting for response from Conn".

I'm trying to get a reliable way to reproducing this, but no luck so far.

**Comment by apersson** [comment]
@mediocregopher, one potential issue that should be eliminated is the non-timeout error path in `reader()`: 

https://github.com/mediocregopher/radix/blob/b2f2f9c16dd56de2b9ad97d083bea5be51029aae/conn.go#L191-L208

Closing the connection like what's done in the partial read case is probably the only safe option.

**Comment by apersson** [comment]
What I believe can happen is the following:

1. Read no. 1: Reset `totalBytesRead`
2. The buffered reader pulls in one complete and one partial response
3. Read no. 1: Returns success
4. Read no. 2: Resets `totalBytesRead`
5. Read no. 2: Consume partial response.
6. Read no. 2: Timeouts out
7. Read no. 2: Bumps `discard` and returns `ErrConnUsable`
8. Read no. 3: The read buffer is now inconsistent as the next read will pull in the remaining response that was for Read no. 2.

**Comment by mediocregopher** [comment]
@apersson do you think we can close this issue? I still intend on fixing #287 but that can be done as part of that issue I think.

**Comment by apersson** [comment]
Yeah, I'm OK to close this out.
