### ISSUE TITLE
Duplicate Pings when creating a PubSub Conn

### ISSUE THREAD

**Issue by MoDa89** [mediocregopher/radix#302]
Hi, in radix-V3 is it possible to remove the internal Ping() call (enclosed in a goroutine) from newPubSub() function ?
since it's only pinging without reporting errors back to the instantiator function.. it's just running there.
I ask for this because I'm calling Ping function from another goroutine, and looking at redis logs
I see duplicate pings when there should be only one!
Thank you.

**Comment by mediocregopher** [comment]
Hi @MoDa89 , this is a pretty low priority change in my opinion, since the extra PING isn't really hurting anything. I agree it's kind of ugly though. Unfortunately we can't modify the `PubSub` function in v3, and I don't think just this feature is worth introducing a whole new PubSubConn constructor to the API.

If you check out the [v4](https://pkg.go.dev/github.com/mediocregopher/radix/v4#PubSubConfig) branch's version of PubSub, however, you'll find that there already exists a way to disable the periodic PINGing. I'd recommend switching over to v4 in the long-run anyway, so I think that's the solution here as well.

Sorry I couldn't directly address your issue this time, but feel free to open more issues in the future for any other questions/suggestions you have.
