### ISSUE TITLE
Unmarshaling problems

### ISSUE THREAD

**Issue by JWestling** [mediocregopher/radix#313]
I am experiencing some unmarshaling errors with Radix when using Redis stream commands. I get a few different signatures:
invalid xread[group] response
expected prefix \"array\", got \"bulk-string\"
can't unmarshal into *[][]string, message body was: \"PONG\"

I think the root cause is that the Redis server have too low cpu and memory limits. In our production test environment (where the above is seen) k8s is used to deploy the Redis server and its limits are set to:
    limits:
      cpu: 50m
      memory: 70Mi
    requests:
      cpu: 30m
      memory: 30Mi
I also see a lot of:
read tcp [ipadress] i/o timeout
(Which also indicates that cpu and memory limits are too low).
In my local test environment where Redis server is deployed using docker without any limits I have never observed these issues.

But even if Redis is misbehaving (due too low cpu limits or other reasons) shouldnt Radix handle the situation. It seems like once the problem starts (Radix and Redis gets "out of sync"?) it seems like it never recovers. If the situation would recover once Redis server gets some "breathing space" I would be fine with it (not much Radix can do about a message from Redis it can not unmarshal other than returning an Error), but that doesnt seem to be the case. I think that Radix should be able to handle this situation better, i.e. recover.

Also is there something that can be done from the application to improve the situation? Configure longer timeouts in Radix? Reconnect to redis when the problem starts? Any other suggestions? 

Maybe this issue is somewhat related to issue #126 (but with different root cause) and #116

**Comment by mediocregopher** [comment]
Hi @JWestling , yes it does sound possible that this is related to #126, and that the client is getting out of sync in some way. Are you able to provide a minimal test case which you're able to replicate the issue with? It would be very helpful to know how exactly you're using radix in order to debug this.

**Comment by JWestling** [comment]
Some update: We have tried to increase the cpu and memory limits, and that did not solve the problem so I think it is something else. I will keep you updated if able to repoduce with a minimal testcase...

**Comment by woodsbury** [comment]
We're facing the same issue after upgrading to Radix v4, and not specifically with stream commands. We've had a few intermittent errors related to unmarshalling the data we've read back from Redis that automatically resolved themselves but have also had one instance where a connection seemed to get stuck in a bad state and caused consistent errors until the application was restarted.

We've attempted to reproduce the problem, and have been able to create a utility that can trigger similar bad behaviour, where one command appears to get another command's response instead of its own. The utility spawns a number of goroutines to send commands to Redis concurrently, with each goroutine randomly choosing to either call a command that will always return success or call a command that will always return an error. Running the utility for long enough you can start to see the "always succeed" branch start getting the errors that the "always error" branch should have received.

Note that this only happens when a context with a deadline is provided (and that deadline occasionally gets exceeded) - if you remove the deadline then the behaviour doesn't seem to occur. I'm suspecting there's an issue somewhere where a deadline has expired and Radix isn't discarding the response, leading to the connection getting out of sync.

[main.txt](https://github.com/mediocregopher/radix/files/9008059/main.txt)

**Comment by woodsbury** [comment]
We've tracked down the issue our utility was triggering to the code that handles discarding responses in `conn.reader()`. When the code unmarshals a response it breaks out of the loop and skips any further reading if it ever gets an error - however it doesn't differentiate between actual errors (say, from the network connection) and normal Redis command errors (say, from a command simply failing, like `redis.error_reply()` will do for a Lua script).

We patched the code locally to confirm that it fixed the problem by changing the following lines in conn.go:

```
if mu.marshal != nil {
	for {
		el := discardList.Front()
		if el == nil {
			break
		}

		discardMU := el.Value.(connMarshalerUnmarshaler)

		if err = resp3.Unmarshal(c.br, discardMU.unmarshalInto, c.rOpts); err != nil {
			// New code below here
			if !errors.As(err, &resp3.SimpleError{}) && !errors.As(err, &resp3.BlobError{}) {
				break
			}

			err = nil
			// New code above here
		}

		discardList.Remove(el)
	}
}
```

I'm not sure if that's the best solution, but it seemed the easiest for us to patch in without having to change too much. With this change our utility doesn't reproduce the problem any more.

**Comment by mediocregopher** [comment]
Thanks @woodsbury , would you be able to submit a PR with your fixed code? I'd like to look at it. As you've probably discovered that whole `Conn` implementation is quite complex, so I wouldn't be surprised if there was a case like this which I missed.

**Comment by mediocregopher** [comment]
Also if you could implement a test case in `conn_test.go` which replicates your testing utility that'd be a great added bonus :)

**Comment by woodsbury** [comment]
Ended up spotting another place in the code (`unmarshalAgg`) that handled a similar issue by setting `DisableErrorBubbling`, so I've made a change that works the same way here. Added a test that reproduced the problem before the changes and passes afterwards.

**Comment by JWestling** [comment]
Sorry for late reply, I see you have already merged a correction and closed the issue.
We made a series of changes to our client application code and eventually the problem disappeared. However, during the troubleshooting we introduced a bug that triggered the problem more frequently. By mistake we did XREADGROUP commands with BLOCK 0, causing no reply from Redis server when there was nothing to consume from the stream. With that bug (in our application code) it caused lots of radix tcp read timeouts. However it seemed like those "hanging" connections (i.e. with tcp read timeout while waiting for something on the stream) were returned to the connection pool and reused for other commands later. Is this how it is implemented in radix (v3)? I think that that could explain the problems we experienced if those "hanging" connections were reused for other commands. The "hanging" connections could also be due to "normal delays" causing radix tcp read timeouts. Maybe connections should be closed at tcp read timeouts even if the connection is fine on tcp level to prevent this kind of problems? @mediocregopher do you think that this could be a problem and should I open an issue for it? (Currently we dont experience the problem anymore since the client application code changes so I dont think I can assist much more).
