### ISSUE TITLE
Radix aware of commands with BLOCK parameter?

### ISSUE THREAD

**Issue by JWestling** [mediocregopher/radix#326]
Does Radix need to be aware of Redis commands with BLOCK parameter (eg. XREADGROUP) and handle them differently?
Eg. maybe TCP read timeout should be adjusted for commands with BLOCK parameter (block time added to read timeout?)?
How are connections supervised by radix? Does radix PING on connections to make sure they are still working? Then maybe radix should not PING on connections that are used for commands with BLOCK parameter (but maybe only "idle" connections (i.e. not used by a command) should be/are supervised?).

**Comment by nussjustin** [comment]
I'll be assuming you are talking about radix v4

> Does Radix need to be aware of Redis commands with BLOCK parameter (eg. XREADGROUP) and handle them differently?
Eg. maybe TCP read timeout should be adjusted for commands with BLOCK parameter (block time added to read timeout?)?

By default no timeout is set for commands. So blocking commands should work correctly.

> How are connections supervised by radix? Does radix PING on connections to make sure they are still working? Then maybe radix should not PING on connections that are used for commands with BLOCK parameter (but maybe only "idle" connections (i.e. not used by a command) should be/are supervised?).

A single connection (created by `Dial`) has no supervision.

Connections that are part of a `Pool` will be `PING`ed every few seconds (by default every `5/<pool size>` seconds). This can be configured with the [https://pkg.go.dev/github.com/mediocregopher/radix/v4#PoolConfig|PoolConfig].

Connections that are currently in use won't be `PING`ed.

Clusters and sentinel both use standard pools underneath and can take a custom `PoolConfig`.

**Comment by mediocregopher** [comment]
Thanks @nussjustin ! Based on @JWestling 's [comment in another issue](https://github.com/mediocregopher/radix/issues/313#issuecomment-1187208774) I think he might be using v3, but everything you wrote remains true there as well, though with one caveats:

Connections in v3 _do_ have an optional read timeout which can be set during `Dial`, and if those are used then some care has to be taken so that BLOCK isn't greater than the read timeout. The documentation for the `Block` field of [StreamReaderOpts](https://pkg.go.dev/github.com/mediocregopher/radix/v3#StreamReaderOpts) describes this.

To address your question from the other issue:

>  Maybe connections should be closed at tcp read timeouts even if the connection is fine on tcp level to prevent this kind of problems?

The Pool implementations in both v3 and v4 currently implement this behavior. We cannot implement this behavior on the connection level, because connections are also used in the context of the SUBSCRIBE command, for which a read timeout is normal.

@JWestling are you using radix's [built in stream reading type](https://pkg.go.dev/github.com/mediocregopher/radix/v3#StreamReader), or have you developed your own? You never specified. If you're implementing your own you'll need to handle the read timeout logic yourself, though you can check out the built in one for reference.

**Comment by JWestling** [comment]
We are using v3 (sorry for not stating clearly) and Pool. 
We use DialTimeout with larger value that BLOCK (10s and 5s).
I was not aware of radix's built in stream reader, so we have developed our own but we will checkout the built in one for reference and see if it solves our problems.

**Comment by mediocregopher** [comment]
@JWestling I'm going to close this for now, feel free to re-open if you have any updates about your issue.
