### ISSUE TITLE
V3: Can the Pool have a maximum connection limit setting?

### ISSUE THREAD

**Issue by itiscold** [mediocregopher/radix#349]
When there is a sudden surge in requests, the connections in the connection pool may become exhausted. To ensure as many requests as possible succeed, we use` PoolOnEmptyCreateAfter(50*time.Millisecond)`.

The problem we face is that a Redis cluster has many clients. If there is a sudden surge in traffic or if Redis experiences a slowdown, it may result in the creation of a large number of connections within a short period, leading to excessive pressure on Redis and potentially causing it to crash.

If we could configure an upper limit on the number of connections, it would not only guarantee a high success rate during peak times but also alleviate concerns about too many connections causing Redis to crash.

**Comment by mediocregopher** [comment]
Hi @itiscold, there's no way to do precisely what you're asking with the v3 Pool. If you use `PoolOnEmptyErrAfter` or `PoolOnEmptyWait` instead of `PoolOnEmptyCreateAfter` then the size of the pool is capped at the size it was initialized with. But this doesn't handle spikes well. If you use `PoolOnFullBuffer` in addition to `PoolOnEmptyCreateAfter` then you can handle spikes better, but there's no cap on the number of connections.

One option could be to supply your own `ConnFunc` via `PoolConnFunc`, and within that ConnFunc track the number of open connections (adding 1 to a counter whenever a Conn is created, subtracting 1 whenever Conn.Close is called). In there you can put whatever limits you like, and decide what you want to do when the limits are reached.

**Comment by itiscold** [comment]
@mediocregopher Thanks for your suggestions! I'll try to limit the maximum number of open connections using my own `ConnFunc`
