### ISSUE TITLE
NewEvalScript

### ISSUE THREAD

**Issue by markschmid** [mediocregopher/radix#46]
A question, not an issue. I don't understand the comment for the example of `NewEvalScript()`. Does "set as global variable" refer to "within redis" or within the Go application?

```// set as a global variable, this script is equivalent to the builtin GETSET
// redis command
var getSet = NewEvalScript(1, `
		local prev = redis.call("GET", KEYS[1])
		redis.call("SET", KEYS[1], ARGV[1])
		return prev
`)
```

In my daemonized application I have a func using `NewEvalScript()` for the same script over and over. Should I keep the `EvalScript` which is generated by `NewEvalScript()` as a global variable so the script is not generated everytime the func is called?

**Comment by nussjustin** [comment]
Yes.

NewEvalScript creates a SHA1 hash of the script which is used to send EVALSHA to the Redis server. Since each call to NewEvalScript has to compute the SHA1 hash again and the EvalScript structs are not linked to a connection / client, you should try to reuse EvalScript instances as much as possible. In the simplest case this can mean putting the instance into a global variable, but you can also put it in struct fields or something else that can be reused.
