### ISSUE TITLE
Check out RedisPipe and figure out if its strategy of implicit pipelining/batching can be incorporated

### ISSUE THREAD

**Issue by mediocregopher** [mediocregopher/radix#58]
https://github.com/joomcode/redispipe

That project essentially uses a batching concept to implicitly pipeline all commands, and uses a WritePause timeout to batch commands together into single system reads/writes. I think doing something similar in radix _might_ be possible, though I haven't really thought out how yet. I think the main challenge will be in coordinating commands across Pool's connections in a way which utilizes the batching to its fullest extent.

**Comment by nussjustin** [comment]
Maybe start with the easy implementation and batch for some duration but allow creating and executing multiple pipelines at the same time (e.g. if one pipeline is executing, and another command is added at the same time then just start a new pipeline with it's own timeout / pause duration.) This should at least automatically make use of connections.

What troubles me is that with radix pipelines currently need to be `CmdAction`'s so we can't just implement an efficient `Client` that pipelines all commands since a `Client` takes alö `Action`'s and not just `CmdAction`s.

**Comment by nussjustin** [comment]
Did some testing and implemented a simple `Conn` wrapper that pipelines `CmdAction`s, while still allowing for non-`CmdAction`s. Code can be found [here](https://github.com/nussjustin/radix.v3/commit/d35b1737595f3851f0c2865e557ed879f8b21376). The code doesn't have tests (only 2 copied tests from action_test.go) but should be working well enough for a quick comparison.

The benchmark result looks good:

```
goos: linux
goarch: amd64
pkg: github.com/mediocregopher/radix/v3
BenchmarkParallelGetSet/radix-8                      100          20195239 ns/op            8149 B/op         36 allocs/op
BenchmarkParallelGetSet/radix_(pipelined)-8               300000              4003 ns/op              71 B/op          4 allocs/op
BenchmarkParallelGetSet/redigo-8                          100000             15364 ns/op             161 B/op          6 allocs/op
PASS
ok      github.com/mediocregopher/radix/v3      5.336s
```

I also had to change the benchmark and multiply the parallelism by 8 (which the redispipe version does too), since otherwise the parallelism was too low so that the pipelined version was always slower.

**Comment by mediocregopher** [comment]
Super cool, do you think this would be something that could be implicitly used by Pool? This also reminds me that somehow the normal benchmark for ParallelGetSet/radix is apparently completely out of whack, @funny-falcon mentioned that to me in the reddit thread.

**Comment by nussjustin** [comment]
I initially wanted to add this to the Pool implicitly (with added `PoolOpt`s to allow opt-out and to configure the window and limit), but I wasn't sure how to integrate it. As you wrote

> I think the main challenge will be in coordinating commands across Pool's connections in a way which utilizes the batching to its fullest extent.

If we can figure this out we can easily add something like my implementation to the Pool by internally wrapping the `Conn`s and maybe even make the whole PipelinedClient package private¹.

¹ I played with the idea of making it both configurable for pools and single connections (via `PoolOpt` and `DialOpt`), but then we would probably need to teach the pool to check it's connections to avoid double pipelining or at least account for it (if it is enabled).

**Comment by mediocregopher** [comment]
Yeah the coordination is definitely gonna be the tricky part, but I think making it implicit in Pool is going to nearly be a requirement, since otherwise most people won't end up using it.

> maybe even make the whole PipelinedClient package private

That would be ideal I think, I would really like to avoid adding more clutter to the API; the docs are pretty big and intimidating as they are. I think to start with, having it be available via `PoolOpt`s only would be fine. Anyone using only a single Conn could get similar behavior with the `Pipeline` Cmd or by calling marshal/unmarshal manually themselves; if they're using Conn in a concurrent way they probably want to be using a Pool anyway. If it turns out to be useful to have PipelinedClient (really PipelinedConn, I think) available publicly in some way that can be added later.

**Comment by nussjustin** [comment]
I tried implementing this directly for `Pool`. The code can be found here: https://github.com/mediocregopher/radix/compare/master...nussjustin:pipelined-poc?expand=1

The current implementation simply pipelines all `CmdAction`'s except thus returned by `WithConn` (does that even implement `CmdAction`? I never checked...), `Pipeline` (to allow better manual pipelining) and custom `CmdAction` implementations (since we don't know the command and we skip pipelining for blocking commands). Multiple pipelines can be executed concurrently (pipeline size, window and concurrency can be configured).

No new tests currently, but there is at least some coverage through the existing tests.

I also fixed a few`cluster tests to close the cluster instances, as they were leaking goroutines which made troubleshooting #60 harder :-)

**Comment by nussjustin** [comment]
For the benchmarks we should probably prefill the pools for radix and redigo before each run. This makes the numbers for the none pipelining case much more stable.

Something like this: https://gist.github.com/nussjustin/e0a668ba45324161ef9df5a742f49411

**Comment by mediocregopher** [comment]
I'm not sure about redigo, but Pool has a private `initDone` channel which can be blocked on to wait until all connections have been created. Perhaps the size of the pool ought to be doubled from what it is now too, in case the test package does slightly more than `parallel` routines at once at any given moment.

**Comment by nussjustin** [comment]
Oh, that works even better.

```
name                                       time/op
SerialGetSet/radix-8                       38.6µs ± 8%
SerialGetSet/redigo-8                      33.2µs ± 3%
SerialGetSet/redispipe-8                    661µs ± 1%
SerialGetSet/redispipe_pause0-8            71.3µs ± 1%
ParallelGetSet/radix/no_pipelining-8       11.8µs ± 4%
ParallelGetSet/radix/one_pipeline-8        4.09µs ± 1%
ParallelGetSet/radix/multiple_pipelines-8  2.21µs ± 5%
ParallelGetSet/redigo-8                    15.0µs ± 4%
ParallelGetSet/redispipe-8                 2.07µs ± 1%

name                                       alloc/op
SerialGetSet/radix-8                        67.0B ± 0%
SerialGetSet/redigo-8                       86.0B ± 0%
SerialGetSet/redispipe-8                     167B ± 0%
SerialGetSet/redispipe_pause0-8              168B ± 0%
ParallelGetSet/radix/no_pipelining-8         116B ± 0%
ParallelGetSet/radix/one_pipeline-8          123B ± 0%
ParallelGetSet/radix/multiple_pipelines-8    125B ± 0%
ParallelGetSet/redigo-8                      128B ± 0%
ParallelGetSet/redispipe-8                   168B ± 0%

name                                       allocs/op
SerialGetSet/radix-8                         4.00 ± 0%
SerialGetSet/redigo-8                        5.00 ± 0%
SerialGetSet/redispipe-8                     8.00 ± 0%
SerialGetSet/redispipe_pause0-8              8.00 ± 0%
ParallelGetSet/radix/no_pipelining-8         6.00 ± 0%
ParallelGetSet/radix/one_pipeline-8          4.00 ± 0%
ParallelGetSet/radix/multiple_pipelines-8    4.00 ± 0%
ParallelGetSet/redigo-8                      6.00 ± 0%
ParallelGetSet/redispipe-8                   8.00 ± 0%
```

Pushed the change to #61

**Comment by funny-falcon** [comment]
It allocates less than redispipe. That is cool :-)
Redispipe uses raw interface{} as result, probably that is the reason.

**Comment by nussjustin** [comment]
@funny-falcon I made sure that it doesn't allocate too much, but never looked at the difference between my implementation and redispipe until now. But yeah, that's cool :-) 

BTW. My implementation also skips pipelining of `WAIT` (https://github.com/mediocregopher/radix/pull/61/files#diff-3c9493b871841c93d7bd777e141fb5ddR19). redispipe does not handle `WAIT`. Since `WAIT` is blocking, redispipe should probably add it to the list of blockings commands too.

**Comment by funny-falcon** [comment]
Yes, you're right about WAIT.

**Comment by funny-falcon** [comment]
That is really great!!!

**Comment by funny-falcon** [comment]
Given your version supports blocking commands (if i understand correctly), it is superrior!

**Comment by mediocregopher** [comment]
PR is merged, went ahead and updated the benchmarks in the README with @nussjustin's numbers. Huge thanks to both of you for all the work on this! :D
