### ISSUE TITLE
Will Pool support max connections setting?

### ISSUE THREAD

**Issue by shrimptttttttttt** [mediocregopher/radix#80]
```func NewPool(network, addr string, size int, opts ...PoolOpt) (*Pool, error)```

NewPool creates a *Pool which will keep open at least the given number of connections to the redis instance at the given address.

So can we limit the max connections be opened?

**Comment by mediocregopher** [comment]
You can check out the PoolOpts for more ways to customize Pool's behavior. NewPool describes what its default PoolOpts are.

The Pool has a "buffer" of connections it can hold, in addition to the `size` given in NewPool. This buffer is used when extra connections are needed during high load, and the extra connections are closed later. You can adjust the size of the buffer (or disable it) by passing `PoolOnFullBuffer(0, 0)` into NewPool.

When an Action is performed on an empty Pool it will, by default, wait 1 second. If a connection doesn't become available in that 1 second it will create a new one. The `PoolOnEmpty*` options can be used to modify this behavior, for example if you'd like the Action to return an error rather than create a new connection you can pass `PoolOnEmptyErrAfter(1 * time.Second)` into NewPool.

By turning off the buffer and not creating new connections when the Pool is empty you limit Pool to only ever making `size` connections. But I'd be careful about doing this, and at least leave the buffer, otherwise if your app goes even slightly over the limit it will grind to a halt.
