### ISSUE TITLE
Is it possible to GET multiple keys that reside in different slots from a single Pipeline call?

### ISSUE THREAD

**Issue by Vistian** [mediocregopher/radix#88]
I am getting the following error: keys "GND9MGDV3A3SEJH" and "GNB4307H7NXJZ98" do not belong to the same slot

`func (db *RedisDatabase) Lookup(keys []string) ([][]byte, error) {

    var responseSlice [][]byte
    var commandSlice []radix.CmdAction

    for idx, value := range keys {
        var response []byte
        responseSlice = append(responseSlice, response)
        commandSlice = append(commandSlice, radix.Cmd(&responseSlice[idx], "GET", value))
    }   

    commandPipeline := radix.Pipeline(commandSlice...)

    err := db.connection.Do(commandPipeline)
    if err != nil {
        log.Printf("Problem querying Redis: %v\n", err)
        return nil, err 
    }   

    return responseSlice, nil 
}`

**Comment by mediocregopher** [comment]
Hi again @Vistian ! You are presumably using the Cluster client to get that error, and those keys don't belong to the same hash slot as defined by redis cluster. Pipeline returns an error because, when using Cluster, the only way for it to be sure that all keys are on the same redis instance is if they belong to the same hash slot.

If a redis instance has more than one slot (as it most likely does) then it's possible to construct a Pipeline which returns that error even if all its keys are on the same redis instance. However, since slots can be moved around arbitrarily in a cluster this shouldn't be expected, and an app shouldn't be designed around that behavior. You can use [hash tags](https://redis.io/topics/cluster-tutorial#redis-cluster-data-sharding) in your key names to control how keys are assigned to slots, and you can use that to group keys together into the same slot which will frequently need to be operated on together (e.g. in a pipeline or transaction).

HOWEVER if you really know what you're doing, and you're sure through some other means that your keys are definitely on the same host, you can do something like this:

```go
type FirstKeyAction struct {
    radix.Action
}

func (fka FirstKeyAction) Keys() []string {
    return []string{fka.Action.Keys()[0]}
}

// ...
// then in your code:
err := client.Do(FirstKeyAction{radix.Pipeline(
    radix.Cmd(...),
    radix.Cmd(...),
)})
```

`FirstKeyAction` will make whatever Action it's wrapping only return a single key, so the check inside the Cluster code will always succeed (but again, if any of the keys which are actually being used are on different hosts, the pipeline will still error out).

Hope that makes sense, lemme know if you have any questions about it.

**Comment by Vistian** [comment]
For to tell you thanks! :-)

**Comment by mediocregopher** [comment]
no problem! glad it helped :)
