### ISSUE TITLE
Questions about using cluster

### ISSUE THREAD

**Issue by kimtree** [mediocregopher/radix#90]
Hi, I got a few questions about using a cluster with your library.

I knew that NewCluster func creates pools for all given hosts (Even if It's a secondary node). But, To send a command with Do func, It only uses primary topo. 

Do you intend to create a pool for all host (including secondary node) at first for reducing the time to create a pool for secondary nodes when the cluster changes suddenly(like secondary node becomes master)? Or Is there another reason?

**Comment by mediocregopher** [comment]
Hi @kimtree! The Cluster code creates a pool for all secondaries in order to help facilitate the `Client` method, so anyone can retrieve a reference to a secondary and have it be already created for them. In addition, as you mentioned, if there is a failover event then the secondary's pool will have already been created.

It would be possible to have the Cluster not create the secondary pools until they are needed, and this is actually what Sentinel's code does, but I haven't put the time into it yet.

Are you finding that the creation of the secondary pools is a problem in some way?

**Comment by kimtree** [comment]
Hi @mediocregopher,
Thanks for the information. I just curious while reading a code. Now I can understand your intention :)

**Comment by mediocregopher** [comment]
Ok! Well feel free to ask me any other questions you have :)
