### ISSUE TITLE
bufio.NewReader(r) use memery too mach

### ISSUE THREAD

**Issue by qq5272689** [mediocregopher/radix#91]
i work with the sentinel module
it's svg https://github.com/qq5272689/test/blob/master/heap_alloc_space.svg

**Comment by nussjustin** [comment]
"too big" is not really helpful.

From what I can guess, your problem are the allocations inside `PubSub`, which come mostly from the call to `bufio.NewReader` inside `resp2.RawMessage.UnmarshalInto`.

In that case, you're right that the code allocates too much and should be optimized to allocate less.

After a quick look I see 2 problems here:

1. The `*bufio.Reader` in `UnmarshalInto` is always created with the default buffer size of 4096 bytes even though we already now the exact number of bytes that are available. For cases where `len(rm) < 4096` we could use `bufio.NewReaderSize` to avoid allocating to much for small messages.
2. The `spin` method of the `pubSubConn` always reads the raw RESP data into a `RawMessage` and after that immediately unmarshals it into a `PubSubMessage`. I don't unterstand why the data is read into a `RawMessage` first. @mediocregopher Any idea?

**Comment by mediocregopher** [comment]
The data is read into a RawMessage first because responses from
PING/(P)(UN)SUBSCRIBE commands also come in through there. So all data is
read into a RawMessage first to be able to determine if it is a
PubSubMessage or not, and discard it if not.

An alternative way to accomplish this, since we don't actually care about
the response from commands, would be to unmarshal directly into
PubSubMessage, and have PubSubMessage.UnmarshalRESP return a specific error
(like `errNotPubSubMessage`) if the data is not a PubSubMessage. The only
caveat would be that the unmarshal method would need to be sure to read the
full response even if the response is not the expected one.

**Comment by qq5272689** [comment]
Thank you so much.

**Comment by mediocregopher** [comment]
I made a further improvement in the last couple of commits, knocking off another bunch of allocations (this is on arm, so exact numbers may vary, and my time/op results were so inconsistent they can probably be ignored):

```
name      old time/op    new time/op    delta
PubSub-4     264µs ±52%     243µs ±52%     ~     (p=0.383 n=20+20)

name      old alloc/op   new alloc/op   delta
PubSub-4      371B ± 1%      160B ± 0%  -56.85%  (p=0.000 n=19+16)

name      old allocs/op  new allocs/op  delta
PubSub-4      10.0 ± 0%       5.0 ± 0%  -50.00%  (p=0.000 n=20+20)
```
