### ISSUE TITLE
Basic SET throwing error in parseUint

### ISSUE THREAD

**Issue by solarfly73** [mediocregopher/radix#94]
I've been running into an issue with v3.2.3 on a SET command, where radix is exiting "invalid character O at position 0 in parseUint".

```
err := clusterClient.Do(radix.Cmd(&rc, "SET", "abc", "123a"))
        if err != nil {
            fmt.Printf("Radix exited with %v\n\n\n", err)
            return false
        }
```
This works from the redis-cli command-line:
```
redis-cli -p 30001 -c
127.0.0.1:30001> SET abc 123a
-> Redirected to slot [7638] located at 127.0.0.1:30006
OK
127.0.0.1:30006> 
```
Am I doing something incorrect?  This error is resulting in failures. Other commands (eg. WAIT and HSET) seem to execute fine.
```
err := clusterClient.Do(radix.Cmd(&rc, "HSET", "efg", "foo", "123a"))
```

**Comment by solarfly73** [comment]
I've done a little more. The `&rc` argument is an int. I was expecting SET to return a status of OK or not. The above example is simplified, as what I was trying to do is this:

```
err := clusterClient.Do(radix.FlatCmd(&rc, "SET", "abc", "123", "NX", "PX", 30000))
```
I was expecting the return code to be nil (0) if the exclusive set fails, or 1 if it succeeds. 
```127.0.0.1:30004> SET fob bar NX PX 30000
OK
127.0.0.1:30004> SET fob bar NX PX 30000
(nil)
```

**Comment by mediocregopher** [comment]
Hi @solarfly73 , for your first example you are trying to unmarshal the return from `SET` into an `int`, but `SET` only ever returns a string reply ("OK"), so you'd need to unmarshal it into a `string` or `[]byte`. But for `SET` with no options I wouldn't even bother unmarshaling the return, since it'll only ever be "OK" or an error:

```go
if err := client.Do(radix.Cmd(nil, "SET", "foo", "bar")); err != nil {
    // handle err
}
// response was "OK"
```

For your second example, once again you are trying to unmarshal a string response into an `int`. However, you'll need to use [MaybeNil](https://godoc.org/github.com/mediocregopher/radix#MaybeNil) in order to handle the case of it returning a `nil` response:

```go
var rc string
mn := radix.MaybeNil{Rcv: &rc}
if err := clusterClient.Do(radix.FlatCmd(&mn, "SET", "abc", "123", "NX", "PX", 30000)); err != nil {
    // handle error
} else if mn.Nil {
    // handle nil response
} else {
    // rc == "OK"
}
```

Once again, since "OK" is the only possible return string, you could just do this instead:

```go
mn := radix.MaybeNil{}
if err := clusterClient.Do(radix.FlatCmd(&mn, "SET", "abc", "123", "NX", "PX", 30000)); err != nil {
    // handle error
} else if mn.Nil {
    // handle nil response
}
// response was "OK"
```

**Comment by solarfly73** [comment]
Oh man I forgot about MaybeNil. Thank you very much for the swift and thorough reply!
